// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: citadel_gcmessages_common.proto

package skadistats.clarity.wire.deadlock.proto;

public final class DeadlockCommonGcMessages {
  private DeadlockCommonGcMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code CMsgLaneColor}
   */
  public enum CMsgLaneColor
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>k_ELaneColor_Invalid = 0;</code>
     */
    k_ELaneColor_Invalid(0, 0),
    /**
     * <code>k_ELaneColor_Yellow = 1;</code>
     */
    k_ELaneColor_Yellow(1, 1),
    /**
     * <code>k_ELaneColor_Green = 3;</code>
     */
    k_ELaneColor_Green(2, 3),
    /**
     * <code>k_ELaneColor_Blue = 4;</code>
     */
    k_ELaneColor_Blue(3, 4),
    /**
     * <code>k_ELaneColor_Purple = 6;</code>
     */
    k_ELaneColor_Purple(4, 6),
    ;

    /**
     * <code>k_ELaneColor_Invalid = 0;</code>
     */
    public static final int k_ELaneColor_Invalid_VALUE = 0;
    /**
     * <code>k_ELaneColor_Yellow = 1;</code>
     */
    public static final int k_ELaneColor_Yellow_VALUE = 1;
    /**
     * <code>k_ELaneColor_Green = 3;</code>
     */
    public static final int k_ELaneColor_Green_VALUE = 3;
    /**
     * <code>k_ELaneColor_Blue = 4;</code>
     */
    public static final int k_ELaneColor_Blue_VALUE = 4;
    /**
     * <code>k_ELaneColor_Purple = 6;</code>
     */
    public static final int k_ELaneColor_Purple_VALUE = 6;


    public final int getNumber() { return value; }

    public static CMsgLaneColor valueOf(int value) {
      switch (value) {
        case 0: return k_ELaneColor_Invalid;
        case 1: return k_ELaneColor_Yellow;
        case 3: return k_ELaneColor_Green;
        case 4: return k_ELaneColor_Blue;
        case 6: return k_ELaneColor_Purple;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CMsgLaneColor>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CMsgLaneColor>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CMsgLaneColor>() {
            public CMsgLaneColor findValueByNumber(int number) {
              return CMsgLaneColor.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return skadistats.clarity.wire.deadlock.proto.DeadlockCommonGcMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final CMsgLaneColor[] VALUES = values();

    public static CMsgLaneColor valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private CMsgLaneColor(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:CMsgLaneColor)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037citadel_gcmessages_common.proto*\212\001\n\rCM" +
      "sgLaneColor\022\030\n\024k_ELaneColor_Invalid\020\000\022\027\n" +
      "\023k_ELaneColor_Yellow\020\001\022\026\n\022k_ELaneColor_G" +
      "reen\020\003\022\025\n\021k_ELaneColor_Blue\020\004\022\027\n\023k_ELane" +
      "Color_Purple\020\006BB\n&skadistats.clarity.wir" +
      "e.deadlock.protoB\030DeadlockCommonGcMessag" +
      "es"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
