// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: s2_dota_usermessages.proto

package skadistats.clarity.wire.dota.s2.proto;

public final class S2DotaUserMessages {
  private S2DotaUserMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code EDotaUserMessages}
   */
  public enum EDotaUserMessages
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DOTA_UM_AddUnitToSelection = 464;</code>
     */
    DOTA_UM_AddUnitToSelection(0, 464),
    /**
     * <code>DOTA_UM_AIDebugLine = 465;</code>
     */
    DOTA_UM_AIDebugLine(1, 465),
    /**
     * <code>DOTA_UM_ChatEvent = 466;</code>
     */
    DOTA_UM_ChatEvent(2, 466),
    /**
     * <code>DOTA_UM_CombatHeroPositions = 467;</code>
     */
    DOTA_UM_CombatHeroPositions(3, 467),
    /**
     * <code>DOTA_UM_CombatLogData = 468;</code>
     */
    DOTA_UM_CombatLogData(4, 468),
    /**
     * <code>DOTA_UM_CombatLogBulkData = 470;</code>
     */
    DOTA_UM_CombatLogBulkData(5, 470),
    /**
     * <code>DOTA_UM_CreateLinearProjectile = 471;</code>
     */
    DOTA_UM_CreateLinearProjectile(6, 471),
    /**
     * <code>DOTA_UM_DestroyLinearProjectile = 472;</code>
     */
    DOTA_UM_DestroyLinearProjectile(7, 472),
    /**
     * <code>DOTA_UM_DodgeTrackingProjectiles = 473;</code>
     */
    DOTA_UM_DodgeTrackingProjectiles(8, 473),
    /**
     * <code>DOTA_UM_GlobalLightColor = 474;</code>
     */
    DOTA_UM_GlobalLightColor(9, 474),
    /**
     * <code>DOTA_UM_GlobalLightDirection = 475;</code>
     */
    DOTA_UM_GlobalLightDirection(10, 475),
    /**
     * <code>DOTA_UM_InvalidCommand = 476;</code>
     */
    DOTA_UM_InvalidCommand(11, 476),
    /**
     * <code>DOTA_UM_LocationPing = 477;</code>
     */
    DOTA_UM_LocationPing(12, 477),
    /**
     * <code>DOTA_UM_MapLine = 478;</code>
     */
    DOTA_UM_MapLine(13, 478),
    /**
     * <code>DOTA_UM_MiniKillCamInfo = 479;</code>
     */
    DOTA_UM_MiniKillCamInfo(14, 479),
    /**
     * <code>DOTA_UM_MinimapDebugPoint = 480;</code>
     */
    DOTA_UM_MinimapDebugPoint(15, 480),
    /**
     * <code>DOTA_UM_MinimapEvent = 481;</code>
     */
    DOTA_UM_MinimapEvent(16, 481),
    /**
     * <code>DOTA_UM_NevermoreRequiem = 482;</code>
     */
    DOTA_UM_NevermoreRequiem(17, 482),
    /**
     * <code>DOTA_UM_OverheadEvent = 483;</code>
     */
    DOTA_UM_OverheadEvent(18, 483),
    /**
     * <code>DOTA_UM_SetNextAutobuyItem = 484;</code>
     */
    DOTA_UM_SetNextAutobuyItem(19, 484),
    /**
     * <code>DOTA_UM_SharedCooldown = 485;</code>
     */
    DOTA_UM_SharedCooldown(20, 485),
    /**
     * <code>DOTA_UM_SpectatorPlayerClick = 486;</code>
     */
    DOTA_UM_SpectatorPlayerClick(21, 486),
    /**
     * <code>DOTA_UM_TutorialTipInfo = 487;</code>
     */
    DOTA_UM_TutorialTipInfo(22, 487),
    /**
     * <code>DOTA_UM_UnitEvent = 488;</code>
     */
    DOTA_UM_UnitEvent(23, 488),
    /**
     * <code>DOTA_UM_ParticleManager = 489;</code>
     */
    DOTA_UM_ParticleManager(24, 489),
    /**
     * <code>DOTA_UM_BotChat = 490;</code>
     */
    DOTA_UM_BotChat(25, 490),
    /**
     * <code>DOTA_UM_HudError = 491;</code>
     */
    DOTA_UM_HudError(26, 491),
    /**
     * <code>DOTA_UM_ItemPurchased = 492;</code>
     */
    DOTA_UM_ItemPurchased(27, 492),
    /**
     * <code>DOTA_UM_Ping = 493;</code>
     */
    DOTA_UM_Ping(28, 493),
    /**
     * <code>DOTA_UM_ItemFound = 494;</code>
     */
    DOTA_UM_ItemFound(29, 494),
    /**
     * <code>DOTA_UM_CharacterSpeakConcept = 495;</code>
     */
    DOTA_UM_CharacterSpeakConcept(30, 495),
    /**
     * <code>DOTA_UM_SwapVerify = 496;</code>
     */
    DOTA_UM_SwapVerify(31, 496),
    /**
     * <code>DOTA_UM_WorldLine = 497;</code>
     */
    DOTA_UM_WorldLine(32, 497),
    /**
     * <code>DOTA_UM_TournamentDrop = 498;</code>
     */
    DOTA_UM_TournamentDrop(33, 498),
    /**
     * <code>DOTA_UM_ItemAlert = 499;</code>
     */
    DOTA_UM_ItemAlert(34, 499),
    /**
     * <code>DOTA_UM_HalloweenDrops = 500;</code>
     */
    DOTA_UM_HalloweenDrops(35, 500),
    /**
     * <code>DOTA_UM_ChatWheel = 501;</code>
     */
    DOTA_UM_ChatWheel(36, 501),
    /**
     * <code>DOTA_UM_ReceivedXmasGift = 502;</code>
     */
    DOTA_UM_ReceivedXmasGift(37, 502),
    /**
     * <code>DOTA_UM_UpdateSharedContent = 503;</code>
     */
    DOTA_UM_UpdateSharedContent(38, 503),
    /**
     * <code>DOTA_UM_TutorialRequestExp = 504;</code>
     */
    DOTA_UM_TutorialRequestExp(39, 504),
    /**
     * <code>DOTA_UM_TutorialPingMinimap = 505;</code>
     */
    DOTA_UM_TutorialPingMinimap(40, 505),
    /**
     * <code>DOTA_UM_GamerulesStateChanged = 506;</code>
     */
    DOTA_UM_GamerulesStateChanged(41, 506),
    /**
     * <code>DOTA_UM_ShowSurvey = 507;</code>
     */
    DOTA_UM_ShowSurvey(42, 507),
    /**
     * <code>DOTA_UM_TutorialFade = 508;</code>
     */
    DOTA_UM_TutorialFade(43, 508),
    /**
     * <code>DOTA_UM_AddQuestLogEntry = 509;</code>
     */
    DOTA_UM_AddQuestLogEntry(44, 509),
    /**
     * <code>DOTA_UM_SendStatPopup = 510;</code>
     */
    DOTA_UM_SendStatPopup(45, 510),
    /**
     * <code>DOTA_UM_TutorialFinish = 511;</code>
     */
    DOTA_UM_TutorialFinish(46, 511),
    /**
     * <code>DOTA_UM_SendRoshanPopup = 512;</code>
     */
    DOTA_UM_SendRoshanPopup(47, 512),
    /**
     * <code>DOTA_UM_SendGenericToolTip = 513;</code>
     */
    DOTA_UM_SendGenericToolTip(48, 513),
    /**
     * <code>DOTA_UM_SendFinalGold = 514;</code>
     */
    DOTA_UM_SendFinalGold(49, 514),
    /**
     * <code>DOTA_UM_CustomMsg = 515;</code>
     */
    DOTA_UM_CustomMsg(50, 515),
    /**
     * <code>DOTA_UM_CoachHUDPing = 516;</code>
     */
    DOTA_UM_CoachHUDPing(51, 516),
    /**
     * <code>DOTA_UM_ClientLoadGridNav = 517;</code>
     */
    DOTA_UM_ClientLoadGridNav(52, 517),
    /**
     * <code>DOTA_UM_TE_Projectile = 518;</code>
     */
    DOTA_UM_TE_Projectile(53, 518),
    /**
     * <code>DOTA_UM_TE_ProjectileLoc = 519;</code>
     */
    DOTA_UM_TE_ProjectileLoc(54, 519),
    /**
     * <code>DOTA_UM_TE_DotaBloodImpact = 520;</code>
     */
    DOTA_UM_TE_DotaBloodImpact(55, 520),
    /**
     * <code>DOTA_UM_TE_UnitAnimation = 521;</code>
     */
    DOTA_UM_TE_UnitAnimation(56, 521),
    /**
     * <code>DOTA_UM_TE_UnitAnimationEnd = 522;</code>
     */
    DOTA_UM_TE_UnitAnimationEnd(57, 522),
    /**
     * <code>DOTA_UM_AbilityPing = 523;</code>
     */
    DOTA_UM_AbilityPing(58, 523),
    /**
     * <code>DOTA_UM_ShowGenericPopup = 524;</code>
     */
    DOTA_UM_ShowGenericPopup(59, 524),
    /**
     * <code>DOTA_UM_VoteStart = 525;</code>
     */
    DOTA_UM_VoteStart(60, 525),
    /**
     * <code>DOTA_UM_VoteUpdate = 526;</code>
     */
    DOTA_UM_VoteUpdate(61, 526),
    /**
     * <code>DOTA_UM_VoteEnd = 527;</code>
     */
    DOTA_UM_VoteEnd(62, 527),
    /**
     * <code>DOTA_UM_BoosterState = 528;</code>
     */
    DOTA_UM_BoosterState(63, 528),
    /**
     * <code>DOTA_UM_WillPurchaseAlert = 529;</code>
     */
    DOTA_UM_WillPurchaseAlert(64, 529),
    /**
     * <code>DOTA_UM_TutorialMinimapPosition = 530;</code>
     */
    DOTA_UM_TutorialMinimapPosition(65, 530),
    /**
     * <code>DOTA_UM_PlayerMMR = 531;</code>
     */
    DOTA_UM_PlayerMMR(66, 531),
    /**
     * <code>DOTA_UM_AbilitySteal = 532;</code>
     */
    DOTA_UM_AbilitySteal(67, 532),
    /**
     * <code>DOTA_UM_CourierKilledAlert = 533;</code>
     */
    DOTA_UM_CourierKilledAlert(68, 533),
    /**
     * <code>DOTA_UM_EnemyItemAlert = 534;</code>
     */
    DOTA_UM_EnemyItemAlert(69, 534),
    /**
     * <code>DOTA_UM_StatsMatchDetails = 535;</code>
     */
    DOTA_UM_StatsMatchDetails(70, 535),
    /**
     * <code>DOTA_UM_MiniTaunt = 536;</code>
     */
    DOTA_UM_MiniTaunt(71, 536),
    /**
     * <code>DOTA_UM_BuyBackStateAlert = 537;</code>
     */
    DOTA_UM_BuyBackStateAlert(72, 537),
    /**
     * <code>DOTA_UM_SpeechBubble = 538;</code>
     */
    DOTA_UM_SpeechBubble(73, 538),
    /**
     * <code>DOTA_UM_CustomHeaderMessage = 539;</code>
     */
    DOTA_UM_CustomHeaderMessage(74, 539),
    /**
     * <code>DOTA_UM_QuickBuyAlert = 540;</code>
     */
    DOTA_UM_QuickBuyAlert(75, 540),
    /**
     * <code>DOTA_UM_StatsHeroDetails = 541;</code>
     */
    DOTA_UM_StatsHeroDetails(76, 541),
    /**
     * <code>DOTA_UM_PredictionResult = 542;</code>
     */
    DOTA_UM_PredictionResult(77, 542),
    /**
     * <code>DOTA_UM_ModifierAlert = 543;</code>
     */
    DOTA_UM_ModifierAlert(78, 543),
    /**
     * <code>DOTA_UM_HPManaAlert = 544;</code>
     */
    DOTA_UM_HPManaAlert(79, 544),
    /**
     * <code>DOTA_UM_GlyphAlert = 545;</code>
     */
    DOTA_UM_GlyphAlert(80, 545),
    /**
     * <code>DOTA_UM_BeastChat = 546;</code>
     */
    DOTA_UM_BeastChat(81, 546),
    /**
     * <code>DOTA_UM_SpectatorPlayerUnitOrders = 547;</code>
     */
    DOTA_UM_SpectatorPlayerUnitOrders(82, 547),
    /**
     * <code>DOTA_UM_CustomHudElement_Create = 548;</code>
     */
    DOTA_UM_CustomHudElement_Create(83, 548),
    /**
     * <code>DOTA_UM_CustomHudElement_Modify = 549;</code>
     */
    DOTA_UM_CustomHudElement_Modify(84, 549),
    /**
     * <code>DOTA_UM_CustomHudElement_Destroy = 550;</code>
     */
    DOTA_UM_CustomHudElement_Destroy(85, 550),
    /**
     * <code>DOTA_UM_CompendiumState = 551;</code>
     */
    DOTA_UM_CompendiumState(86, 551),
    /**
     * <code>DOTA_UM_ProjectionAbility = 552;</code>
     */
    DOTA_UM_ProjectionAbility(87, 552),
    /**
     * <code>DOTA_UM_ProjectionEvent = 553;</code>
     */
    DOTA_UM_ProjectionEvent(88, 553),
    /**
     * <code>DOTA_UM_CombatLogDataHLTV = 554;</code>
     */
    DOTA_UM_CombatLogDataHLTV(89, 554),
    /**
     * <code>DOTA_UM_XPAlert = 555;</code>
     */
    DOTA_UM_XPAlert(90, 555),
    /**
     * <code>DOTA_UM_UpdateQuestProgress = 556;</code>
     */
    DOTA_UM_UpdateQuestProgress(91, 556),
    /**
     * <code>DOTA_UM_MatchMetadata = 557;</code>
     */
    DOTA_UM_MatchMetadata(92, 557),
    /**
     * <code>DOTA_UM_MatchDetails = 558;</code>
     */
    DOTA_UM_MatchDetails(93, 558),
    /**
     * <code>DOTA_UM_QuestStatus = 559;</code>
     */
    DOTA_UM_QuestStatus(94, 559),
    /**
     * <code>DOTA_UM_SuggestHeroPick = 560;</code>
     */
    DOTA_UM_SuggestHeroPick(95, 560),
    /**
     * <code>DOTA_UM_SuggestHeroRole = 561;</code>
     */
    DOTA_UM_SuggestHeroRole(96, 561),
    /**
     * <code>DOTA_UM_KillcamDamageTaken = 562;</code>
     */
    DOTA_UM_KillcamDamageTaken(97, 562),
    /**
     * <code>DOTA_UM_SelectPenaltyGold = 563;</code>
     */
    DOTA_UM_SelectPenaltyGold(98, 563),
    /**
     * <code>DOTA_UM_RollDiceResult = 564;</code>
     */
    DOTA_UM_RollDiceResult(99, 564),
    /**
     * <code>DOTA_UM_FlipCoinResult = 565;</code>
     */
    DOTA_UM_FlipCoinResult(100, 565),
    /**
     * <code>DOTA_UM_RequestItemSuggestions = 566;</code>
     */
    DOTA_UM_RequestItemSuggestions(101, 566),
    /**
     * <code>DOTA_UM_TeamCaptainChanged = 567;</code>
     */
    DOTA_UM_TeamCaptainChanged(102, 567),
    /**
     * <code>DOTA_UM_SendRoshanSpectatorPhase = 568;</code>
     */
    DOTA_UM_SendRoshanSpectatorPhase(103, 568),
    /**
     * <code>DOTA_UM_ChatWheelCooldown = 569;</code>
     */
    DOTA_UM_ChatWheelCooldown(104, 569),
    /**
     * <code>DOTA_UM_DismissAllStatPopups = 570;</code>
     */
    DOTA_UM_DismissAllStatPopups(105, 570),
    /**
     * <code>DOTA_UM_TE_DestroyProjectile = 571;</code>
     */
    DOTA_UM_TE_DestroyProjectile(106, 571),
    /**
     * <code>DOTA_UM_HeroRelicProgress = 572;</code>
     */
    DOTA_UM_HeroRelicProgress(107, 572),
    /**
     * <code>DOTA_UM_AbilityDraftRequestAbility = 573;</code>
     */
    DOTA_UM_AbilityDraftRequestAbility(108, 573),
    /**
     * <code>DOTA_UM_ItemSold = 574;</code>
     */
    DOTA_UM_ItemSold(109, 574),
    /**
     * <code>DOTA_UM_DamageReport = 575;</code>
     */
    DOTA_UM_DamageReport(110, 575),
    /**
     * <code>DOTA_UM_SalutePlayer = 576;</code>
     */
    DOTA_UM_SalutePlayer(111, 576),
    /**
     * <code>DOTA_UM_TipAlert = 577;</code>
     */
    DOTA_UM_TipAlert(112, 577),
    /**
     * <code>DOTA_UM_ReplaceQueryUnit = 578;</code>
     */
    DOTA_UM_ReplaceQueryUnit(113, 578),
    /**
     * <code>DOTA_UM_EmptyTeleportAlert = 579;</code>
     */
    DOTA_UM_EmptyTeleportAlert(114, 579),
    /**
     * <code>DOTA_UM_MarsArenaOfBloodAttack = 580;</code>
     */
    DOTA_UM_MarsArenaOfBloodAttack(115, 580),
    /**
     * <code>DOTA_UM_ESArcanaCombo = 581;</code>
     */
    DOTA_UM_ESArcanaCombo(116, 581),
    /**
     * <code>DOTA_UM_ESArcanaComboSummary = 582;</code>
     */
    DOTA_UM_ESArcanaComboSummary(117, 582),
    /**
     * <code>DOTA_UM_HighFiveLeftHanging = 583;</code>
     */
    DOTA_UM_HighFiveLeftHanging(118, 583),
    /**
     * <code>DOTA_UM_HighFiveCompleted = 584;</code>
     */
    DOTA_UM_HighFiveCompleted(119, 584),
    /**
     * <code>DOTA_UM_ShovelUnearth = 585;</code>
     */
    DOTA_UM_ShovelUnearth(120, 585),
    /**
     * <code>DOTA_EM_InvokerSpellCast = 586;</code>
     */
    DOTA_EM_InvokerSpellCast(121, 586),
    /**
     * <code>DOTA_UM_RadarAlert = 587;</code>
     */
    DOTA_UM_RadarAlert(122, 587),
    /**
     * <code>DOTA_UM_AllStarEvent = 588;</code>
     */
    DOTA_UM_AllStarEvent(123, 588),
    /**
     * <code>DOTA_UM_TalentTreeAlert = 589;</code>
     */
    DOTA_UM_TalentTreeAlert(124, 589),
    /**
     * <code>DOTA_UM_QueuedOrderRemoved = 590;</code>
     */
    DOTA_UM_QueuedOrderRemoved(125, 590),
    /**
     * <code>DOTA_UM_DebugChallenge = 591;</code>
     */
    DOTA_UM_DebugChallenge(126, 591),
    /**
     * <code>DOTA_UM_OMArcanaCombo = 592;</code>
     */
    DOTA_UM_OMArcanaCombo(127, 592),
    /**
     * <code>DOTA_UM_FoundNeutralItem = 593;</code>
     */
    DOTA_UM_FoundNeutralItem(128, 593),
    /**
     * <code>DOTA_UM_OutpostCaptured = 594;</code>
     */
    DOTA_UM_OutpostCaptured(129, 594),
    /**
     * <code>DOTA_UM_OutpostGrantedXP = 595;</code>
     */
    DOTA_UM_OutpostGrantedXP(130, 595),
    /**
     * <code>DOTA_UM_MoveCameraToUnit = 596;</code>
     */
    DOTA_UM_MoveCameraToUnit(131, 596),
    /**
     * <code>DOTA_UM_PauseMinigameData = 597;</code>
     */
    DOTA_UM_PauseMinigameData(132, 597),
    /**
     * <code>DOTA_UM_VersusScene_PlayerBehavior = 598;</code>
     */
    DOTA_UM_VersusScene_PlayerBehavior(133, 598),
    /**
     * <code>DOTA_UM_QoP_ArcanaSummary = 600;</code>
     */
    DOTA_UM_QoP_ArcanaSummary(134, 600),
    /**
     * <code>DOTA_UM_HotPotato_Created = 601;</code>
     */
    DOTA_UM_HotPotato_Created(135, 601),
    /**
     * <code>DOTA_UM_HotPotato_Exploded = 602;</code>
     */
    DOTA_UM_HotPotato_Exploded(136, 602),
    /**
     * <code>DOTA_UM_WK_Arcana_Progress = 603;</code>
     */
    DOTA_UM_WK_Arcana_Progress(137, 603),
    /**
     * <code>DOTA_UM_GuildChallenge_Progress = 604;</code>
     */
    DOTA_UM_GuildChallenge_Progress(138, 604),
    /**
     * <code>DOTA_UM_WRArcanaProgress = 605;</code>
     */
    DOTA_UM_WRArcanaProgress(139, 605),
    /**
     * <code>DOTA_UM_WRArcanaSummary = 606;</code>
     */
    DOTA_UM_WRArcanaSummary(140, 606),
    /**
     * <code>DOTA_UM_EmptyItemSlotAlert = 607;</code>
     */
    DOTA_UM_EmptyItemSlotAlert(141, 607),
    /**
     * <code>DOTA_UM_AghsStatusAlert = 608;</code>
     */
    DOTA_UM_AghsStatusAlert(142, 608),
    /**
     * <code>DOTA_UM_PingConfirmation = 609;</code>
     */
    DOTA_UM_PingConfirmation(143, 609),
    /**
     * <code>DOTA_UM_MutedPlayers = 610;</code>
     */
    DOTA_UM_MutedPlayers(144, 610),
    /**
     * <code>DOTA_UM_ContextualTip = 611;</code>
     */
    DOTA_UM_ContextualTip(145, 611),
    /**
     * <code>DOTA_UM_ChatMessage = 612;</code>
     */
    DOTA_UM_ChatMessage(146, 612),
    /**
     * <code>DOTA_UM_NeutralCampAlert = 613;</code>
     */
    DOTA_UM_NeutralCampAlert(147, 613),
    /**
     * <code>DOTA_UM_RockPaperScissorsStarted = 614;</code>
     */
    DOTA_UM_RockPaperScissorsStarted(148, 614),
    /**
     * <code>DOTA_UM_RockPaperScissorsFinished = 615;</code>
     */
    DOTA_UM_RockPaperScissorsFinished(149, 615),
    /**
     * <code>DOTA_UM_DuelOpponentKilled = 616;</code>
     */
    DOTA_UM_DuelOpponentKilled(150, 616),
    /**
     * <code>DOTA_UM_DuelAccepted = 617;</code>
     */
    DOTA_UM_DuelAccepted(151, 617),
    /**
     * <code>DOTA_UM_DuelRequested = 618;</code>
     */
    DOTA_UM_DuelRequested(152, 618),
    /**
     * <code>DOTA_UM_MuertaReleaseEvent_AssignedTargetKilled = 619;</code>
     */
    DOTA_UM_MuertaReleaseEvent_AssignedTargetKilled(153, 619),
    /**
     * <code>DOTA_UM_PlayerDraftSuggestPick = 620;</code>
     */
    DOTA_UM_PlayerDraftSuggestPick(154, 620),
    /**
     * <code>DOTA_UM_PlayerDraftPick = 621;</code>
     */
    DOTA_UM_PlayerDraftPick(155, 621),
    ;

    /**
     * <code>DOTA_UM_AddUnitToSelection = 464;</code>
     */
    public static final int DOTA_UM_AddUnitToSelection_VALUE = 464;
    /**
     * <code>DOTA_UM_AIDebugLine = 465;</code>
     */
    public static final int DOTA_UM_AIDebugLine_VALUE = 465;
    /**
     * <code>DOTA_UM_ChatEvent = 466;</code>
     */
    public static final int DOTA_UM_ChatEvent_VALUE = 466;
    /**
     * <code>DOTA_UM_CombatHeroPositions = 467;</code>
     */
    public static final int DOTA_UM_CombatHeroPositions_VALUE = 467;
    /**
     * <code>DOTA_UM_CombatLogData = 468;</code>
     */
    public static final int DOTA_UM_CombatLogData_VALUE = 468;
    /**
     * <code>DOTA_UM_CombatLogBulkData = 470;</code>
     */
    public static final int DOTA_UM_CombatLogBulkData_VALUE = 470;
    /**
     * <code>DOTA_UM_CreateLinearProjectile = 471;</code>
     */
    public static final int DOTA_UM_CreateLinearProjectile_VALUE = 471;
    /**
     * <code>DOTA_UM_DestroyLinearProjectile = 472;</code>
     */
    public static final int DOTA_UM_DestroyLinearProjectile_VALUE = 472;
    /**
     * <code>DOTA_UM_DodgeTrackingProjectiles = 473;</code>
     */
    public static final int DOTA_UM_DodgeTrackingProjectiles_VALUE = 473;
    /**
     * <code>DOTA_UM_GlobalLightColor = 474;</code>
     */
    public static final int DOTA_UM_GlobalLightColor_VALUE = 474;
    /**
     * <code>DOTA_UM_GlobalLightDirection = 475;</code>
     */
    public static final int DOTA_UM_GlobalLightDirection_VALUE = 475;
    /**
     * <code>DOTA_UM_InvalidCommand = 476;</code>
     */
    public static final int DOTA_UM_InvalidCommand_VALUE = 476;
    /**
     * <code>DOTA_UM_LocationPing = 477;</code>
     */
    public static final int DOTA_UM_LocationPing_VALUE = 477;
    /**
     * <code>DOTA_UM_MapLine = 478;</code>
     */
    public static final int DOTA_UM_MapLine_VALUE = 478;
    /**
     * <code>DOTA_UM_MiniKillCamInfo = 479;</code>
     */
    public static final int DOTA_UM_MiniKillCamInfo_VALUE = 479;
    /**
     * <code>DOTA_UM_MinimapDebugPoint = 480;</code>
     */
    public static final int DOTA_UM_MinimapDebugPoint_VALUE = 480;
    /**
     * <code>DOTA_UM_MinimapEvent = 481;</code>
     */
    public static final int DOTA_UM_MinimapEvent_VALUE = 481;
    /**
     * <code>DOTA_UM_NevermoreRequiem = 482;</code>
     */
    public static final int DOTA_UM_NevermoreRequiem_VALUE = 482;
    /**
     * <code>DOTA_UM_OverheadEvent = 483;</code>
     */
    public static final int DOTA_UM_OverheadEvent_VALUE = 483;
    /**
     * <code>DOTA_UM_SetNextAutobuyItem = 484;</code>
     */
    public static final int DOTA_UM_SetNextAutobuyItem_VALUE = 484;
    /**
     * <code>DOTA_UM_SharedCooldown = 485;</code>
     */
    public static final int DOTA_UM_SharedCooldown_VALUE = 485;
    /**
     * <code>DOTA_UM_SpectatorPlayerClick = 486;</code>
     */
    public static final int DOTA_UM_SpectatorPlayerClick_VALUE = 486;
    /**
     * <code>DOTA_UM_TutorialTipInfo = 487;</code>
     */
    public static final int DOTA_UM_TutorialTipInfo_VALUE = 487;
    /**
     * <code>DOTA_UM_UnitEvent = 488;</code>
     */
    public static final int DOTA_UM_UnitEvent_VALUE = 488;
    /**
     * <code>DOTA_UM_ParticleManager = 489;</code>
     */
    public static final int DOTA_UM_ParticleManager_VALUE = 489;
    /**
     * <code>DOTA_UM_BotChat = 490;</code>
     */
    public static final int DOTA_UM_BotChat_VALUE = 490;
    /**
     * <code>DOTA_UM_HudError = 491;</code>
     */
    public static final int DOTA_UM_HudError_VALUE = 491;
    /**
     * <code>DOTA_UM_ItemPurchased = 492;</code>
     */
    public static final int DOTA_UM_ItemPurchased_VALUE = 492;
    /**
     * <code>DOTA_UM_Ping = 493;</code>
     */
    public static final int DOTA_UM_Ping_VALUE = 493;
    /**
     * <code>DOTA_UM_ItemFound = 494;</code>
     */
    public static final int DOTA_UM_ItemFound_VALUE = 494;
    /**
     * <code>DOTA_UM_CharacterSpeakConcept = 495;</code>
     */
    public static final int DOTA_UM_CharacterSpeakConcept_VALUE = 495;
    /**
     * <code>DOTA_UM_SwapVerify = 496;</code>
     */
    public static final int DOTA_UM_SwapVerify_VALUE = 496;
    /**
     * <code>DOTA_UM_WorldLine = 497;</code>
     */
    public static final int DOTA_UM_WorldLine_VALUE = 497;
    /**
     * <code>DOTA_UM_TournamentDrop = 498;</code>
     */
    public static final int DOTA_UM_TournamentDrop_VALUE = 498;
    /**
     * <code>DOTA_UM_ItemAlert = 499;</code>
     */
    public static final int DOTA_UM_ItemAlert_VALUE = 499;
    /**
     * <code>DOTA_UM_HalloweenDrops = 500;</code>
     */
    public static final int DOTA_UM_HalloweenDrops_VALUE = 500;
    /**
     * <code>DOTA_UM_ChatWheel = 501;</code>
     */
    public static final int DOTA_UM_ChatWheel_VALUE = 501;
    /**
     * <code>DOTA_UM_ReceivedXmasGift = 502;</code>
     */
    public static final int DOTA_UM_ReceivedXmasGift_VALUE = 502;
    /**
     * <code>DOTA_UM_UpdateSharedContent = 503;</code>
     */
    public static final int DOTA_UM_UpdateSharedContent_VALUE = 503;
    /**
     * <code>DOTA_UM_TutorialRequestExp = 504;</code>
     */
    public static final int DOTA_UM_TutorialRequestExp_VALUE = 504;
    /**
     * <code>DOTA_UM_TutorialPingMinimap = 505;</code>
     */
    public static final int DOTA_UM_TutorialPingMinimap_VALUE = 505;
    /**
     * <code>DOTA_UM_GamerulesStateChanged = 506;</code>
     */
    public static final int DOTA_UM_GamerulesStateChanged_VALUE = 506;
    /**
     * <code>DOTA_UM_ShowSurvey = 507;</code>
     */
    public static final int DOTA_UM_ShowSurvey_VALUE = 507;
    /**
     * <code>DOTA_UM_TutorialFade = 508;</code>
     */
    public static final int DOTA_UM_TutorialFade_VALUE = 508;
    /**
     * <code>DOTA_UM_AddQuestLogEntry = 509;</code>
     */
    public static final int DOTA_UM_AddQuestLogEntry_VALUE = 509;
    /**
     * <code>DOTA_UM_SendStatPopup = 510;</code>
     */
    public static final int DOTA_UM_SendStatPopup_VALUE = 510;
    /**
     * <code>DOTA_UM_TutorialFinish = 511;</code>
     */
    public static final int DOTA_UM_TutorialFinish_VALUE = 511;
    /**
     * <code>DOTA_UM_SendRoshanPopup = 512;</code>
     */
    public static final int DOTA_UM_SendRoshanPopup_VALUE = 512;
    /**
     * <code>DOTA_UM_SendGenericToolTip = 513;</code>
     */
    public static final int DOTA_UM_SendGenericToolTip_VALUE = 513;
    /**
     * <code>DOTA_UM_SendFinalGold = 514;</code>
     */
    public static final int DOTA_UM_SendFinalGold_VALUE = 514;
    /**
     * <code>DOTA_UM_CustomMsg = 515;</code>
     */
    public static final int DOTA_UM_CustomMsg_VALUE = 515;
    /**
     * <code>DOTA_UM_CoachHUDPing = 516;</code>
     */
    public static final int DOTA_UM_CoachHUDPing_VALUE = 516;
    /**
     * <code>DOTA_UM_ClientLoadGridNav = 517;</code>
     */
    public static final int DOTA_UM_ClientLoadGridNav_VALUE = 517;
    /**
     * <code>DOTA_UM_TE_Projectile = 518;</code>
     */
    public static final int DOTA_UM_TE_Projectile_VALUE = 518;
    /**
     * <code>DOTA_UM_TE_ProjectileLoc = 519;</code>
     */
    public static final int DOTA_UM_TE_ProjectileLoc_VALUE = 519;
    /**
     * <code>DOTA_UM_TE_DotaBloodImpact = 520;</code>
     */
    public static final int DOTA_UM_TE_DotaBloodImpact_VALUE = 520;
    /**
     * <code>DOTA_UM_TE_UnitAnimation = 521;</code>
     */
    public static final int DOTA_UM_TE_UnitAnimation_VALUE = 521;
    /**
     * <code>DOTA_UM_TE_UnitAnimationEnd = 522;</code>
     */
    public static final int DOTA_UM_TE_UnitAnimationEnd_VALUE = 522;
    /**
     * <code>DOTA_UM_AbilityPing = 523;</code>
     */
    public static final int DOTA_UM_AbilityPing_VALUE = 523;
    /**
     * <code>DOTA_UM_ShowGenericPopup = 524;</code>
     */
    public static final int DOTA_UM_ShowGenericPopup_VALUE = 524;
    /**
     * <code>DOTA_UM_VoteStart = 525;</code>
     */
    public static final int DOTA_UM_VoteStart_VALUE = 525;
    /**
     * <code>DOTA_UM_VoteUpdate = 526;</code>
     */
    public static final int DOTA_UM_VoteUpdate_VALUE = 526;
    /**
     * <code>DOTA_UM_VoteEnd = 527;</code>
     */
    public static final int DOTA_UM_VoteEnd_VALUE = 527;
    /**
     * <code>DOTA_UM_BoosterState = 528;</code>
     */
    public static final int DOTA_UM_BoosterState_VALUE = 528;
    /**
     * <code>DOTA_UM_WillPurchaseAlert = 529;</code>
     */
    public static final int DOTA_UM_WillPurchaseAlert_VALUE = 529;
    /**
     * <code>DOTA_UM_TutorialMinimapPosition = 530;</code>
     */
    public static final int DOTA_UM_TutorialMinimapPosition_VALUE = 530;
    /**
     * <code>DOTA_UM_PlayerMMR = 531;</code>
     */
    public static final int DOTA_UM_PlayerMMR_VALUE = 531;
    /**
     * <code>DOTA_UM_AbilitySteal = 532;</code>
     */
    public static final int DOTA_UM_AbilitySteal_VALUE = 532;
    /**
     * <code>DOTA_UM_CourierKilledAlert = 533;</code>
     */
    public static final int DOTA_UM_CourierKilledAlert_VALUE = 533;
    /**
     * <code>DOTA_UM_EnemyItemAlert = 534;</code>
     */
    public static final int DOTA_UM_EnemyItemAlert_VALUE = 534;
    /**
     * <code>DOTA_UM_StatsMatchDetails = 535;</code>
     */
    public static final int DOTA_UM_StatsMatchDetails_VALUE = 535;
    /**
     * <code>DOTA_UM_MiniTaunt = 536;</code>
     */
    public static final int DOTA_UM_MiniTaunt_VALUE = 536;
    /**
     * <code>DOTA_UM_BuyBackStateAlert = 537;</code>
     */
    public static final int DOTA_UM_BuyBackStateAlert_VALUE = 537;
    /**
     * <code>DOTA_UM_SpeechBubble = 538;</code>
     */
    public static final int DOTA_UM_SpeechBubble_VALUE = 538;
    /**
     * <code>DOTA_UM_CustomHeaderMessage = 539;</code>
     */
    public static final int DOTA_UM_CustomHeaderMessage_VALUE = 539;
    /**
     * <code>DOTA_UM_QuickBuyAlert = 540;</code>
     */
    public static final int DOTA_UM_QuickBuyAlert_VALUE = 540;
    /**
     * <code>DOTA_UM_StatsHeroDetails = 541;</code>
     */
    public static final int DOTA_UM_StatsHeroDetails_VALUE = 541;
    /**
     * <code>DOTA_UM_PredictionResult = 542;</code>
     */
    public static final int DOTA_UM_PredictionResult_VALUE = 542;
    /**
     * <code>DOTA_UM_ModifierAlert = 543;</code>
     */
    public static final int DOTA_UM_ModifierAlert_VALUE = 543;
    /**
     * <code>DOTA_UM_HPManaAlert = 544;</code>
     */
    public static final int DOTA_UM_HPManaAlert_VALUE = 544;
    /**
     * <code>DOTA_UM_GlyphAlert = 545;</code>
     */
    public static final int DOTA_UM_GlyphAlert_VALUE = 545;
    /**
     * <code>DOTA_UM_BeastChat = 546;</code>
     */
    public static final int DOTA_UM_BeastChat_VALUE = 546;
    /**
     * <code>DOTA_UM_SpectatorPlayerUnitOrders = 547;</code>
     */
    public static final int DOTA_UM_SpectatorPlayerUnitOrders_VALUE = 547;
    /**
     * <code>DOTA_UM_CustomHudElement_Create = 548;</code>
     */
    public static final int DOTA_UM_CustomHudElement_Create_VALUE = 548;
    /**
     * <code>DOTA_UM_CustomHudElement_Modify = 549;</code>
     */
    public static final int DOTA_UM_CustomHudElement_Modify_VALUE = 549;
    /**
     * <code>DOTA_UM_CustomHudElement_Destroy = 550;</code>
     */
    public static final int DOTA_UM_CustomHudElement_Destroy_VALUE = 550;
    /**
     * <code>DOTA_UM_CompendiumState = 551;</code>
     */
    public static final int DOTA_UM_CompendiumState_VALUE = 551;
    /**
     * <code>DOTA_UM_ProjectionAbility = 552;</code>
     */
    public static final int DOTA_UM_ProjectionAbility_VALUE = 552;
    /**
     * <code>DOTA_UM_ProjectionEvent = 553;</code>
     */
    public static final int DOTA_UM_ProjectionEvent_VALUE = 553;
    /**
     * <code>DOTA_UM_CombatLogDataHLTV = 554;</code>
     */
    public static final int DOTA_UM_CombatLogDataHLTV_VALUE = 554;
    /**
     * <code>DOTA_UM_XPAlert = 555;</code>
     */
    public static final int DOTA_UM_XPAlert_VALUE = 555;
    /**
     * <code>DOTA_UM_UpdateQuestProgress = 556;</code>
     */
    public static final int DOTA_UM_UpdateQuestProgress_VALUE = 556;
    /**
     * <code>DOTA_UM_MatchMetadata = 557;</code>
     */
    public static final int DOTA_UM_MatchMetadata_VALUE = 557;
    /**
     * <code>DOTA_UM_MatchDetails = 558;</code>
     */
    public static final int DOTA_UM_MatchDetails_VALUE = 558;
    /**
     * <code>DOTA_UM_QuestStatus = 559;</code>
     */
    public static final int DOTA_UM_QuestStatus_VALUE = 559;
    /**
     * <code>DOTA_UM_SuggestHeroPick = 560;</code>
     */
    public static final int DOTA_UM_SuggestHeroPick_VALUE = 560;
    /**
     * <code>DOTA_UM_SuggestHeroRole = 561;</code>
     */
    public static final int DOTA_UM_SuggestHeroRole_VALUE = 561;
    /**
     * <code>DOTA_UM_KillcamDamageTaken = 562;</code>
     */
    public static final int DOTA_UM_KillcamDamageTaken_VALUE = 562;
    /**
     * <code>DOTA_UM_SelectPenaltyGold = 563;</code>
     */
    public static final int DOTA_UM_SelectPenaltyGold_VALUE = 563;
    /**
     * <code>DOTA_UM_RollDiceResult = 564;</code>
     */
    public static final int DOTA_UM_RollDiceResult_VALUE = 564;
    /**
     * <code>DOTA_UM_FlipCoinResult = 565;</code>
     */
    public static final int DOTA_UM_FlipCoinResult_VALUE = 565;
    /**
     * <code>DOTA_UM_RequestItemSuggestions = 566;</code>
     */
    public static final int DOTA_UM_RequestItemSuggestions_VALUE = 566;
    /**
     * <code>DOTA_UM_TeamCaptainChanged = 567;</code>
     */
    public static final int DOTA_UM_TeamCaptainChanged_VALUE = 567;
    /**
     * <code>DOTA_UM_SendRoshanSpectatorPhase = 568;</code>
     */
    public static final int DOTA_UM_SendRoshanSpectatorPhase_VALUE = 568;
    /**
     * <code>DOTA_UM_ChatWheelCooldown = 569;</code>
     */
    public static final int DOTA_UM_ChatWheelCooldown_VALUE = 569;
    /**
     * <code>DOTA_UM_DismissAllStatPopups = 570;</code>
     */
    public static final int DOTA_UM_DismissAllStatPopups_VALUE = 570;
    /**
     * <code>DOTA_UM_TE_DestroyProjectile = 571;</code>
     */
    public static final int DOTA_UM_TE_DestroyProjectile_VALUE = 571;
    /**
     * <code>DOTA_UM_HeroRelicProgress = 572;</code>
     */
    public static final int DOTA_UM_HeroRelicProgress_VALUE = 572;
    /**
     * <code>DOTA_UM_AbilityDraftRequestAbility = 573;</code>
     */
    public static final int DOTA_UM_AbilityDraftRequestAbility_VALUE = 573;
    /**
     * <code>DOTA_UM_ItemSold = 574;</code>
     */
    public static final int DOTA_UM_ItemSold_VALUE = 574;
    /**
     * <code>DOTA_UM_DamageReport = 575;</code>
     */
    public static final int DOTA_UM_DamageReport_VALUE = 575;
    /**
     * <code>DOTA_UM_SalutePlayer = 576;</code>
     */
    public static final int DOTA_UM_SalutePlayer_VALUE = 576;
    /**
     * <code>DOTA_UM_TipAlert = 577;</code>
     */
    public static final int DOTA_UM_TipAlert_VALUE = 577;
    /**
     * <code>DOTA_UM_ReplaceQueryUnit = 578;</code>
     */
    public static final int DOTA_UM_ReplaceQueryUnit_VALUE = 578;
    /**
     * <code>DOTA_UM_EmptyTeleportAlert = 579;</code>
     */
    public static final int DOTA_UM_EmptyTeleportAlert_VALUE = 579;
    /**
     * <code>DOTA_UM_MarsArenaOfBloodAttack = 580;</code>
     */
    public static final int DOTA_UM_MarsArenaOfBloodAttack_VALUE = 580;
    /**
     * <code>DOTA_UM_ESArcanaCombo = 581;</code>
     */
    public static final int DOTA_UM_ESArcanaCombo_VALUE = 581;
    /**
     * <code>DOTA_UM_ESArcanaComboSummary = 582;</code>
     */
    public static final int DOTA_UM_ESArcanaComboSummary_VALUE = 582;
    /**
     * <code>DOTA_UM_HighFiveLeftHanging = 583;</code>
     */
    public static final int DOTA_UM_HighFiveLeftHanging_VALUE = 583;
    /**
     * <code>DOTA_UM_HighFiveCompleted = 584;</code>
     */
    public static final int DOTA_UM_HighFiveCompleted_VALUE = 584;
    /**
     * <code>DOTA_UM_ShovelUnearth = 585;</code>
     */
    public static final int DOTA_UM_ShovelUnearth_VALUE = 585;
    /**
     * <code>DOTA_EM_InvokerSpellCast = 586;</code>
     */
    public static final int DOTA_EM_InvokerSpellCast_VALUE = 586;
    /**
     * <code>DOTA_UM_RadarAlert = 587;</code>
     */
    public static final int DOTA_UM_RadarAlert_VALUE = 587;
    /**
     * <code>DOTA_UM_AllStarEvent = 588;</code>
     */
    public static final int DOTA_UM_AllStarEvent_VALUE = 588;
    /**
     * <code>DOTA_UM_TalentTreeAlert = 589;</code>
     */
    public static final int DOTA_UM_TalentTreeAlert_VALUE = 589;
    /**
     * <code>DOTA_UM_QueuedOrderRemoved = 590;</code>
     */
    public static final int DOTA_UM_QueuedOrderRemoved_VALUE = 590;
    /**
     * <code>DOTA_UM_DebugChallenge = 591;</code>
     */
    public static final int DOTA_UM_DebugChallenge_VALUE = 591;
    /**
     * <code>DOTA_UM_OMArcanaCombo = 592;</code>
     */
    public static final int DOTA_UM_OMArcanaCombo_VALUE = 592;
    /**
     * <code>DOTA_UM_FoundNeutralItem = 593;</code>
     */
    public static final int DOTA_UM_FoundNeutralItem_VALUE = 593;
    /**
     * <code>DOTA_UM_OutpostCaptured = 594;</code>
     */
    public static final int DOTA_UM_OutpostCaptured_VALUE = 594;
    /**
     * <code>DOTA_UM_OutpostGrantedXP = 595;</code>
     */
    public static final int DOTA_UM_OutpostGrantedXP_VALUE = 595;
    /**
     * <code>DOTA_UM_MoveCameraToUnit = 596;</code>
     */
    public static final int DOTA_UM_MoveCameraToUnit_VALUE = 596;
    /**
     * <code>DOTA_UM_PauseMinigameData = 597;</code>
     */
    public static final int DOTA_UM_PauseMinigameData_VALUE = 597;
    /**
     * <code>DOTA_UM_VersusScene_PlayerBehavior = 598;</code>
     */
    public static final int DOTA_UM_VersusScene_PlayerBehavior_VALUE = 598;
    /**
     * <code>DOTA_UM_QoP_ArcanaSummary = 600;</code>
     */
    public static final int DOTA_UM_QoP_ArcanaSummary_VALUE = 600;
    /**
     * <code>DOTA_UM_HotPotato_Created = 601;</code>
     */
    public static final int DOTA_UM_HotPotato_Created_VALUE = 601;
    /**
     * <code>DOTA_UM_HotPotato_Exploded = 602;</code>
     */
    public static final int DOTA_UM_HotPotato_Exploded_VALUE = 602;
    /**
     * <code>DOTA_UM_WK_Arcana_Progress = 603;</code>
     */
    public static final int DOTA_UM_WK_Arcana_Progress_VALUE = 603;
    /**
     * <code>DOTA_UM_GuildChallenge_Progress = 604;</code>
     */
    public static final int DOTA_UM_GuildChallenge_Progress_VALUE = 604;
    /**
     * <code>DOTA_UM_WRArcanaProgress = 605;</code>
     */
    public static final int DOTA_UM_WRArcanaProgress_VALUE = 605;
    /**
     * <code>DOTA_UM_WRArcanaSummary = 606;</code>
     */
    public static final int DOTA_UM_WRArcanaSummary_VALUE = 606;
    /**
     * <code>DOTA_UM_EmptyItemSlotAlert = 607;</code>
     */
    public static final int DOTA_UM_EmptyItemSlotAlert_VALUE = 607;
    /**
     * <code>DOTA_UM_AghsStatusAlert = 608;</code>
     */
    public static final int DOTA_UM_AghsStatusAlert_VALUE = 608;
    /**
     * <code>DOTA_UM_PingConfirmation = 609;</code>
     */
    public static final int DOTA_UM_PingConfirmation_VALUE = 609;
    /**
     * <code>DOTA_UM_MutedPlayers = 610;</code>
     */
    public static final int DOTA_UM_MutedPlayers_VALUE = 610;
    /**
     * <code>DOTA_UM_ContextualTip = 611;</code>
     */
    public static final int DOTA_UM_ContextualTip_VALUE = 611;
    /**
     * <code>DOTA_UM_ChatMessage = 612;</code>
     */
    public static final int DOTA_UM_ChatMessage_VALUE = 612;
    /**
     * <code>DOTA_UM_NeutralCampAlert = 613;</code>
     */
    public static final int DOTA_UM_NeutralCampAlert_VALUE = 613;
    /**
     * <code>DOTA_UM_RockPaperScissorsStarted = 614;</code>
     */
    public static final int DOTA_UM_RockPaperScissorsStarted_VALUE = 614;
    /**
     * <code>DOTA_UM_RockPaperScissorsFinished = 615;</code>
     */
    public static final int DOTA_UM_RockPaperScissorsFinished_VALUE = 615;
    /**
     * <code>DOTA_UM_DuelOpponentKilled = 616;</code>
     */
    public static final int DOTA_UM_DuelOpponentKilled_VALUE = 616;
    /**
     * <code>DOTA_UM_DuelAccepted = 617;</code>
     */
    public static final int DOTA_UM_DuelAccepted_VALUE = 617;
    /**
     * <code>DOTA_UM_DuelRequested = 618;</code>
     */
    public static final int DOTA_UM_DuelRequested_VALUE = 618;
    /**
     * <code>DOTA_UM_MuertaReleaseEvent_AssignedTargetKilled = 619;</code>
     */
    public static final int DOTA_UM_MuertaReleaseEvent_AssignedTargetKilled_VALUE = 619;
    /**
     * <code>DOTA_UM_PlayerDraftSuggestPick = 620;</code>
     */
    public static final int DOTA_UM_PlayerDraftSuggestPick_VALUE = 620;
    /**
     * <code>DOTA_UM_PlayerDraftPick = 621;</code>
     */
    public static final int DOTA_UM_PlayerDraftPick_VALUE = 621;


    public final int getNumber() { return value; }

    public static EDotaUserMessages valueOf(int value) {
      switch (value) {
        case 464: return DOTA_UM_AddUnitToSelection;
        case 465: return DOTA_UM_AIDebugLine;
        case 466: return DOTA_UM_ChatEvent;
        case 467: return DOTA_UM_CombatHeroPositions;
        case 468: return DOTA_UM_CombatLogData;
        case 470: return DOTA_UM_CombatLogBulkData;
        case 471: return DOTA_UM_CreateLinearProjectile;
        case 472: return DOTA_UM_DestroyLinearProjectile;
        case 473: return DOTA_UM_DodgeTrackingProjectiles;
        case 474: return DOTA_UM_GlobalLightColor;
        case 475: return DOTA_UM_GlobalLightDirection;
        case 476: return DOTA_UM_InvalidCommand;
        case 477: return DOTA_UM_LocationPing;
        case 478: return DOTA_UM_MapLine;
        case 479: return DOTA_UM_MiniKillCamInfo;
        case 480: return DOTA_UM_MinimapDebugPoint;
        case 481: return DOTA_UM_MinimapEvent;
        case 482: return DOTA_UM_NevermoreRequiem;
        case 483: return DOTA_UM_OverheadEvent;
        case 484: return DOTA_UM_SetNextAutobuyItem;
        case 485: return DOTA_UM_SharedCooldown;
        case 486: return DOTA_UM_SpectatorPlayerClick;
        case 487: return DOTA_UM_TutorialTipInfo;
        case 488: return DOTA_UM_UnitEvent;
        case 489: return DOTA_UM_ParticleManager;
        case 490: return DOTA_UM_BotChat;
        case 491: return DOTA_UM_HudError;
        case 492: return DOTA_UM_ItemPurchased;
        case 493: return DOTA_UM_Ping;
        case 494: return DOTA_UM_ItemFound;
        case 495: return DOTA_UM_CharacterSpeakConcept;
        case 496: return DOTA_UM_SwapVerify;
        case 497: return DOTA_UM_WorldLine;
        case 498: return DOTA_UM_TournamentDrop;
        case 499: return DOTA_UM_ItemAlert;
        case 500: return DOTA_UM_HalloweenDrops;
        case 501: return DOTA_UM_ChatWheel;
        case 502: return DOTA_UM_ReceivedXmasGift;
        case 503: return DOTA_UM_UpdateSharedContent;
        case 504: return DOTA_UM_TutorialRequestExp;
        case 505: return DOTA_UM_TutorialPingMinimap;
        case 506: return DOTA_UM_GamerulesStateChanged;
        case 507: return DOTA_UM_ShowSurvey;
        case 508: return DOTA_UM_TutorialFade;
        case 509: return DOTA_UM_AddQuestLogEntry;
        case 510: return DOTA_UM_SendStatPopup;
        case 511: return DOTA_UM_TutorialFinish;
        case 512: return DOTA_UM_SendRoshanPopup;
        case 513: return DOTA_UM_SendGenericToolTip;
        case 514: return DOTA_UM_SendFinalGold;
        case 515: return DOTA_UM_CustomMsg;
        case 516: return DOTA_UM_CoachHUDPing;
        case 517: return DOTA_UM_ClientLoadGridNav;
        case 518: return DOTA_UM_TE_Projectile;
        case 519: return DOTA_UM_TE_ProjectileLoc;
        case 520: return DOTA_UM_TE_DotaBloodImpact;
        case 521: return DOTA_UM_TE_UnitAnimation;
        case 522: return DOTA_UM_TE_UnitAnimationEnd;
        case 523: return DOTA_UM_AbilityPing;
        case 524: return DOTA_UM_ShowGenericPopup;
        case 525: return DOTA_UM_VoteStart;
        case 526: return DOTA_UM_VoteUpdate;
        case 527: return DOTA_UM_VoteEnd;
        case 528: return DOTA_UM_BoosterState;
        case 529: return DOTA_UM_WillPurchaseAlert;
        case 530: return DOTA_UM_TutorialMinimapPosition;
        case 531: return DOTA_UM_PlayerMMR;
        case 532: return DOTA_UM_AbilitySteal;
        case 533: return DOTA_UM_CourierKilledAlert;
        case 534: return DOTA_UM_EnemyItemAlert;
        case 535: return DOTA_UM_StatsMatchDetails;
        case 536: return DOTA_UM_MiniTaunt;
        case 537: return DOTA_UM_BuyBackStateAlert;
        case 538: return DOTA_UM_SpeechBubble;
        case 539: return DOTA_UM_CustomHeaderMessage;
        case 540: return DOTA_UM_QuickBuyAlert;
        case 541: return DOTA_UM_StatsHeroDetails;
        case 542: return DOTA_UM_PredictionResult;
        case 543: return DOTA_UM_ModifierAlert;
        case 544: return DOTA_UM_HPManaAlert;
        case 545: return DOTA_UM_GlyphAlert;
        case 546: return DOTA_UM_BeastChat;
        case 547: return DOTA_UM_SpectatorPlayerUnitOrders;
        case 548: return DOTA_UM_CustomHudElement_Create;
        case 549: return DOTA_UM_CustomHudElement_Modify;
        case 550: return DOTA_UM_CustomHudElement_Destroy;
        case 551: return DOTA_UM_CompendiumState;
        case 552: return DOTA_UM_ProjectionAbility;
        case 553: return DOTA_UM_ProjectionEvent;
        case 554: return DOTA_UM_CombatLogDataHLTV;
        case 555: return DOTA_UM_XPAlert;
        case 556: return DOTA_UM_UpdateQuestProgress;
        case 557: return DOTA_UM_MatchMetadata;
        case 558: return DOTA_UM_MatchDetails;
        case 559: return DOTA_UM_QuestStatus;
        case 560: return DOTA_UM_SuggestHeroPick;
        case 561: return DOTA_UM_SuggestHeroRole;
        case 562: return DOTA_UM_KillcamDamageTaken;
        case 563: return DOTA_UM_SelectPenaltyGold;
        case 564: return DOTA_UM_RollDiceResult;
        case 565: return DOTA_UM_FlipCoinResult;
        case 566: return DOTA_UM_RequestItemSuggestions;
        case 567: return DOTA_UM_TeamCaptainChanged;
        case 568: return DOTA_UM_SendRoshanSpectatorPhase;
        case 569: return DOTA_UM_ChatWheelCooldown;
        case 570: return DOTA_UM_DismissAllStatPopups;
        case 571: return DOTA_UM_TE_DestroyProjectile;
        case 572: return DOTA_UM_HeroRelicProgress;
        case 573: return DOTA_UM_AbilityDraftRequestAbility;
        case 574: return DOTA_UM_ItemSold;
        case 575: return DOTA_UM_DamageReport;
        case 576: return DOTA_UM_SalutePlayer;
        case 577: return DOTA_UM_TipAlert;
        case 578: return DOTA_UM_ReplaceQueryUnit;
        case 579: return DOTA_UM_EmptyTeleportAlert;
        case 580: return DOTA_UM_MarsArenaOfBloodAttack;
        case 581: return DOTA_UM_ESArcanaCombo;
        case 582: return DOTA_UM_ESArcanaComboSummary;
        case 583: return DOTA_UM_HighFiveLeftHanging;
        case 584: return DOTA_UM_HighFiveCompleted;
        case 585: return DOTA_UM_ShovelUnearth;
        case 586: return DOTA_EM_InvokerSpellCast;
        case 587: return DOTA_UM_RadarAlert;
        case 588: return DOTA_UM_AllStarEvent;
        case 589: return DOTA_UM_TalentTreeAlert;
        case 590: return DOTA_UM_QueuedOrderRemoved;
        case 591: return DOTA_UM_DebugChallenge;
        case 592: return DOTA_UM_OMArcanaCombo;
        case 593: return DOTA_UM_FoundNeutralItem;
        case 594: return DOTA_UM_OutpostCaptured;
        case 595: return DOTA_UM_OutpostGrantedXP;
        case 596: return DOTA_UM_MoveCameraToUnit;
        case 597: return DOTA_UM_PauseMinigameData;
        case 598: return DOTA_UM_VersusScene_PlayerBehavior;
        case 600: return DOTA_UM_QoP_ArcanaSummary;
        case 601: return DOTA_UM_HotPotato_Created;
        case 602: return DOTA_UM_HotPotato_Exploded;
        case 603: return DOTA_UM_WK_Arcana_Progress;
        case 604: return DOTA_UM_GuildChallenge_Progress;
        case 605: return DOTA_UM_WRArcanaProgress;
        case 606: return DOTA_UM_WRArcanaSummary;
        case 607: return DOTA_UM_EmptyItemSlotAlert;
        case 608: return DOTA_UM_AghsStatusAlert;
        case 609: return DOTA_UM_PingConfirmation;
        case 610: return DOTA_UM_MutedPlayers;
        case 611: return DOTA_UM_ContextualTip;
        case 612: return DOTA_UM_ChatMessage;
        case 613: return DOTA_UM_NeutralCampAlert;
        case 614: return DOTA_UM_RockPaperScissorsStarted;
        case 615: return DOTA_UM_RockPaperScissorsFinished;
        case 616: return DOTA_UM_DuelOpponentKilled;
        case 617: return DOTA_UM_DuelAccepted;
        case 618: return DOTA_UM_DuelRequested;
        case 619: return DOTA_UM_MuertaReleaseEvent_AssignedTargetKilled;
        case 620: return DOTA_UM_PlayerDraftSuggestPick;
        case 621: return DOTA_UM_PlayerDraftPick;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EDotaUserMessages>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<EDotaUserMessages>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EDotaUserMessages>() {
            public EDotaUserMessages findValueByNumber(int number) {
              return EDotaUserMessages.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return skadistats.clarity.wire.dota.s2.proto.S2DotaUserMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final EDotaUserMessages[] VALUES = values();

    public static EDotaUserMessages valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private EDotaUserMessages(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EDotaUserMessages)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032s2_dota_usermessages.proto*\244%\n\021EDotaUs" +
      "erMessages\022\037\n\032DOTA_UM_AddUnitToSelection" +
      "\020\320\003\022\030\n\023DOTA_UM_AIDebugLine\020\321\003\022\026\n\021DOTA_UM" +
      "_ChatEvent\020\322\003\022 \n\033DOTA_UM_CombatHeroPosit" +
      "ions\020\323\003\022\032\n\025DOTA_UM_CombatLogData\020\324\003\022\036\n\031D" +
      "OTA_UM_CombatLogBulkData\020\326\003\022#\n\036DOTA_UM_C" +
      "reateLinearProjectile\020\327\003\022$\n\037DOTA_UM_Dest" +
      "royLinearProjectile\020\330\003\022%\n DOTA_UM_DodgeT" +
      "rackingProjectiles\020\331\003\022\035\n\030DOTA_UM_GlobalL" +
      "ightColor\020\332\003\022!\n\034DOTA_UM_GlobalLightDirec",
      "tion\020\333\003\022\033\n\026DOTA_UM_InvalidCommand\020\334\003\022\031\n\024" +
      "DOTA_UM_LocationPing\020\335\003\022\024\n\017DOTA_UM_MapLi" +
      "ne\020\336\003\022\034\n\027DOTA_UM_MiniKillCamInfo\020\337\003\022\036\n\031D" +
      "OTA_UM_MinimapDebugPoint\020\340\003\022\031\n\024DOTA_UM_M" +
      "inimapEvent\020\341\003\022\035\n\030DOTA_UM_NevermoreRequi" +
      "em\020\342\003\022\032\n\025DOTA_UM_OverheadEvent\020\343\003\022\037\n\032DOT" +
      "A_UM_SetNextAutobuyItem\020\344\003\022\033\n\026DOTA_UM_Sh" +
      "aredCooldown\020\345\003\022!\n\034DOTA_UM_SpectatorPlay" +
      "erClick\020\346\003\022\034\n\027DOTA_UM_TutorialTipInfo\020\347\003" +
      "\022\026\n\021DOTA_UM_UnitEvent\020\350\003\022\034\n\027DOTA_UM_Part",
      "icleManager\020\351\003\022\024\n\017DOTA_UM_BotChat\020\352\003\022\025\n\020" +
      "DOTA_UM_HudError\020\353\003\022\032\n\025DOTA_UM_ItemPurch" +
      "ased\020\354\003\022\021\n\014DOTA_UM_Ping\020\355\003\022\026\n\021DOTA_UM_It" +
      "emFound\020\356\003\022\"\n\035DOTA_UM_CharacterSpeakConc" +
      "ept\020\357\003\022\027\n\022DOTA_UM_SwapVerify\020\360\003\022\026\n\021DOTA_" +
      "UM_WorldLine\020\361\003\022\033\n\026DOTA_UM_TournamentDro" +
      "p\020\362\003\022\026\n\021DOTA_UM_ItemAlert\020\363\003\022\033\n\026DOTA_UM_" +
      "HalloweenDrops\020\364\003\022\026\n\021DOTA_UM_ChatWheel\020\365" +
      "\003\022\035\n\030DOTA_UM_ReceivedXmasGift\020\366\003\022 \n\033DOTA" +
      "_UM_UpdateSharedContent\020\367\003\022\037\n\032DOTA_UM_Tu",
      "torialRequestExp\020\370\003\022 \n\033DOTA_UM_TutorialP" +
      "ingMinimap\020\371\003\022\"\n\035DOTA_UM_GamerulesStateC" +
      "hanged\020\372\003\022\027\n\022DOTA_UM_ShowSurvey\020\373\003\022\031\n\024DO" +
      "TA_UM_TutorialFade\020\374\003\022\035\n\030DOTA_UM_AddQues" +
      "tLogEntry\020\375\003\022\032\n\025DOTA_UM_SendStatPopup\020\376\003" +
      "\022\033\n\026DOTA_UM_TutorialFinish\020\377\003\022\034\n\027DOTA_UM" +
      "_SendRoshanPopup\020\200\004\022\037\n\032DOTA_UM_SendGener" +
      "icToolTip\020\201\004\022\032\n\025DOTA_UM_SendFinalGold\020\202\004" +
      "\022\026\n\021DOTA_UM_CustomMsg\020\203\004\022\031\n\024DOTA_UM_Coac" +
      "hHUDPing\020\204\004\022\036\n\031DOTA_UM_ClientLoadGridNav",
      "\020\205\004\022\032\n\025DOTA_UM_TE_Projectile\020\206\004\022\035\n\030DOTA_" +
      "UM_TE_ProjectileLoc\020\207\004\022\037\n\032DOTA_UM_TE_Dot" +
      "aBloodImpact\020\210\004\022\035\n\030DOTA_UM_TE_UnitAnimat" +
      "ion\020\211\004\022 \n\033DOTA_UM_TE_UnitAnimationEnd\020\212\004" +
      "\022\030\n\023DOTA_UM_AbilityPing\020\213\004\022\035\n\030DOTA_UM_Sh" +
      "owGenericPopup\020\214\004\022\026\n\021DOTA_UM_VoteStart\020\215" +
      "\004\022\027\n\022DOTA_UM_VoteUpdate\020\216\004\022\024\n\017DOTA_UM_Vo" +
      "teEnd\020\217\004\022\031\n\024DOTA_UM_BoosterState\020\220\004\022\036\n\031D" +
      "OTA_UM_WillPurchaseAlert\020\221\004\022$\n\037DOTA_UM_T" +
      "utorialMinimapPosition\020\222\004\022\026\n\021DOTA_UM_Pla",
      "yerMMR\020\223\004\022\031\n\024DOTA_UM_AbilitySteal\020\224\004\022\037\n\032" +
      "DOTA_UM_CourierKilledAlert\020\225\004\022\033\n\026DOTA_UM" +
      "_EnemyItemAlert\020\226\004\022\036\n\031DOTA_UM_StatsMatch" +
      "Details\020\227\004\022\026\n\021DOTA_UM_MiniTaunt\020\230\004\022\036\n\031DO" +
      "TA_UM_BuyBackStateAlert\020\231\004\022\031\n\024DOTA_UM_Sp" +
      "eechBubble\020\232\004\022 \n\033DOTA_UM_CustomHeaderMes" +
      "sage\020\233\004\022\032\n\025DOTA_UM_QuickBuyAlert\020\234\004\022\035\n\030D" +
      "OTA_UM_StatsHeroDetails\020\235\004\022\035\n\030DOTA_UM_Pr" +
      "edictionResult\020\236\004\022\032\n\025DOTA_UM_ModifierAle" +
      "rt\020\237\004\022\030\n\023DOTA_UM_HPManaAlert\020\240\004\022\027\n\022DOTA_",
      "UM_GlyphAlert\020\241\004\022\026\n\021DOTA_UM_BeastChat\020\242\004" +
      "\022&\n!DOTA_UM_SpectatorPlayerUnitOrders\020\243\004" +
      "\022$\n\037DOTA_UM_CustomHudElement_Create\020\244\004\022$" +
      "\n\037DOTA_UM_CustomHudElement_Modify\020\245\004\022%\n " +
      "DOTA_UM_CustomHudElement_Destroy\020\246\004\022\034\n\027D" +
      "OTA_UM_CompendiumState\020\247\004\022\036\n\031DOTA_UM_Pro" +
      "jectionAbility\020\250\004\022\034\n\027DOTA_UM_ProjectionE" +
      "vent\020\251\004\022\036\n\031DOTA_UM_CombatLogDataHLTV\020\252\004\022" +
      "\024\n\017DOTA_UM_XPAlert\020\253\004\022 \n\033DOTA_UM_UpdateQ" +
      "uestProgress\020\254\004\022\032\n\025DOTA_UM_MatchMetadata",
      "\020\255\004\022\031\n\024DOTA_UM_MatchDetails\020\256\004\022\030\n\023DOTA_U" +
      "M_QuestStatus\020\257\004\022\034\n\027DOTA_UM_SuggestHeroP" +
      "ick\020\260\004\022\034\n\027DOTA_UM_SuggestHeroRole\020\261\004\022\037\n\032" +
      "DOTA_UM_KillcamDamageTaken\020\262\004\022\036\n\031DOTA_UM" +
      "_SelectPenaltyGold\020\263\004\022\033\n\026DOTA_UM_RollDic" +
      "eResult\020\264\004\022\033\n\026DOTA_UM_FlipCoinResult\020\265\004\022" +
      "#\n\036DOTA_UM_RequestItemSuggestions\020\266\004\022\037\n\032" +
      "DOTA_UM_TeamCaptainChanged\020\267\004\022%\n DOTA_UM" +
      "_SendRoshanSpectatorPhase\020\270\004\022\036\n\031DOTA_UM_" +
      "ChatWheelCooldown\020\271\004\022!\n\034DOTA_UM_DismissA",
      "llStatPopups\020\272\004\022!\n\034DOTA_UM_TE_DestroyPro" +
      "jectile\020\273\004\022\036\n\031DOTA_UM_HeroRelicProgress\020" +
      "\274\004\022\'\n\"DOTA_UM_AbilityDraftRequestAbility" +
      "\020\275\004\022\025\n\020DOTA_UM_ItemSold\020\276\004\022\031\n\024DOTA_UM_Da" +
      "mageReport\020\277\004\022\031\n\024DOTA_UM_SalutePlayer\020\300\004" +
      "\022\025\n\020DOTA_UM_TipAlert\020\301\004\022\035\n\030DOTA_UM_Repla" +
      "ceQueryUnit\020\302\004\022\037\n\032DOTA_UM_EmptyTeleportA" +
      "lert\020\303\004\022#\n\036DOTA_UM_MarsArenaOfBloodAttac" +
      "k\020\304\004\022\032\n\025DOTA_UM_ESArcanaCombo\020\305\004\022!\n\034DOTA" +
      "_UM_ESArcanaComboSummary\020\306\004\022 \n\033DOTA_UM_H",
      "ighFiveLeftHanging\020\307\004\022\036\n\031DOTA_UM_HighFiv" +
      "eCompleted\020\310\004\022\032\n\025DOTA_UM_ShovelUnearth\020\311" +
      "\004\022\035\n\030DOTA_EM_InvokerSpellCast\020\312\004\022\027\n\022DOTA" +
      "_UM_RadarAlert\020\313\004\022\031\n\024DOTA_UM_AllStarEven" +
      "t\020\314\004\022\034\n\027DOTA_UM_TalentTreeAlert\020\315\004\022\037\n\032DO" +
      "TA_UM_QueuedOrderRemoved\020\316\004\022\033\n\026DOTA_UM_D" +
      "ebugChallenge\020\317\004\022\032\n\025DOTA_UM_OMArcanaComb" +
      "o\020\320\004\022\035\n\030DOTA_UM_FoundNeutralItem\020\321\004\022\034\n\027D" +
      "OTA_UM_OutpostCaptured\020\322\004\022\035\n\030DOTA_UM_Out" +
      "postGrantedXP\020\323\004\022\035\n\030DOTA_UM_MoveCameraTo",
      "Unit\020\324\004\022\036\n\031DOTA_UM_PauseMinigameData\020\325\004\022" +
      "\'\n\"DOTA_UM_VersusScene_PlayerBehavior\020\326\004" +
      "\022\036\n\031DOTA_UM_QoP_ArcanaSummary\020\330\004\022\036\n\031DOTA" +
      "_UM_HotPotato_Created\020\331\004\022\037\n\032DOTA_UM_HotP" +
      "otato_Exploded\020\332\004\022\037\n\032DOTA_UM_WK_Arcana_P" +
      "rogress\020\333\004\022$\n\037DOTA_UM_GuildChallenge_Pro" +
      "gress\020\334\004\022\035\n\030DOTA_UM_WRArcanaProgress\020\335\004\022" +
      "\034\n\027DOTA_UM_WRArcanaSummary\020\336\004\022\037\n\032DOTA_UM" +
      "_EmptyItemSlotAlert\020\337\004\022\034\n\027DOTA_UM_AghsSt" +
      "atusAlert\020\340\004\022\035\n\030DOTA_UM_PingConfirmation",
      "\020\341\004\022\031\n\024DOTA_UM_MutedPlayers\020\342\004\022\032\n\025DOTA_U" +
      "M_ContextualTip\020\343\004\022\030\n\023DOTA_UM_ChatMessag" +
      "e\020\344\004\022\035\n\030DOTA_UM_NeutralCampAlert\020\345\004\022%\n D" +
      "OTA_UM_RockPaperScissorsStarted\020\346\004\022&\n!DO" +
      "TA_UM_RockPaperScissorsFinished\020\347\004\022\037\n\032DO" +
      "TA_UM_DuelOpponentKilled\020\350\004\022\031\n\024DOTA_UM_D" +
      "uelAccepted\020\351\004\022\032\n\025DOTA_UM_DuelRequested\020" +
      "\352\004\0224\n/DOTA_UM_MuertaReleaseEvent_Assigne" +
      "dTargetKilled\020\353\004\022#\n\036DOTA_UM_PlayerDraftS" +
      "uggestPick\020\354\004\022\034\n\027DOTA_UM_PlayerDraftPick",
      "\020\355\004B@\n%skadistats.clarity.wire.dota.s2.p" +
      "rotoB\022S2DotaUserMessagesH\001\200\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
