package skadistats.clarity.wire.dota.s2;

import com.google.protobuf.GeneratedMessage;
import skadistats.clarity.wire.ClassToKindMessageRegistry;
import skadistats.clarity.wire.KindToClassMessageRegistry;
import skadistats.clarity.wire.dota.common.proto.DOTAUserMessages;
import skadistats.clarity.wire.dota.s2.proto.DOTAS2GcMessagesCommon;
import skadistats.clarity.wire.dota.s2.proto.DOTAS2MatchMetadata;
import skadistats.clarity.wire.dota.s2.proto.DOTAS2MessageId;
import skadistats.clarity.wire.shared.common.proto.CommonNetMessages;
import skadistats.clarity.wire.shared.common.proto.CommonNetworkBaseTypes;
import skadistats.clarity.wire.shared.demo.proto.DemoNetMessages;
import skadistats.clarity.wire.shared.demo.proto.DemoUserMessages;
import skadistats.clarity.wire.shared.s2.proto.S2GameEvents;
import skadistats.clarity.wire.shared.s2.proto.S2NetMessages;
import skadistats.clarity.wire.shared.s2.proto.S2NetworkBaseTypes;
import skadistats.clarity.wire.shared.s2.proto.S2TempEntities;
import skadistats.clarity.wire.shared.s2.proto.S2UserMessages;

public class EmbeddedPackets {

    private static final KindToClassMessageRegistry K2C;

    static {
        K2C = new KindToClassMessageRegistry(100);
        /*   0 */ K2C.put(DOTAS2MessageId.NET_Messages.net_NOP_VALUE, CommonNetworkBaseTypes.CNETMsg_NOP.class);
        /*   1 */ K2C.put(DOTAS2MessageId.NET_Messages.net_Disconnect_VALUE, CommonNetworkBaseTypes.CNETMsg_Disconnect.class);
        /*   4 */ K2C.put(DOTAS2MessageId.NET_Messages.net_Tick_VALUE, CommonNetworkBaseTypes.CNETMsg_Tick.class);
        /*   6 */ K2C.put(DOTAS2MessageId.NET_Messages.net_SetConVar_VALUE, CommonNetworkBaseTypes.CNETMsg_SetConVar.class);
        /*   7 */ K2C.put(DOTAS2MessageId.NET_Messages.net_SignonState_VALUE, CommonNetworkBaseTypes.CNETMsg_SignonState.class);
        /*   8 */ K2C.put(DOTAS2MessageId.NET_Messages.net_SpawnGroup_Load_VALUE, S2NetworkBaseTypes.CNETMsg_SpawnGroup_Load.class);
        /*   9 */ K2C.put(DOTAS2MessageId.NET_Messages.net_SpawnGroup_ManifestUpdate_VALUE, S2NetworkBaseTypes.CNETMsg_SpawnGroup_ManifestUpdate.class);
        /*  11 */ K2C.put(DOTAS2MessageId.NET_Messages.net_SpawnGroup_SetCreationTick_VALUE, S2NetworkBaseTypes.CNETMsg_SpawnGroup_SetCreationTick.class);
        /*  12 */ K2C.put(DOTAS2MessageId.NET_Messages.net_SpawnGroup_Unload_VALUE, S2NetworkBaseTypes.CNETMsg_SpawnGroup_Unload.class);
        /*  12 */ K2C.put(DOTAS2MessageId.NET_Messages.net_SpawnGroup_LoadCompleted_VALUE, S2NetworkBaseTypes.CNETMsg_SpawnGroup_LoadCompleted.class);

        /*  20 */ K2C.put(DOTAS2MessageId.CLC_Messages.clc_ClientInfo_VALUE, CommonNetMessages.CCLCMsg_ClientInfo.class);
        /*  21 */ K2C.put(DOTAS2MessageId.CLC_Messages.clc_Move_VALUE, CommonNetMessages.CCLCMsg_Move.class);
        /*  23 */ K2C.put(DOTAS2MessageId.CLC_Messages.clc_BaselineAck_VALUE, CommonNetMessages.CCLCMsg_BaselineAck.class);
        /*  27 */ K2C.put(DOTAS2MessageId.CLC_Messages.clc_LoadingProgress_VALUE, CommonNetMessages.CCLCMsg_LoadingProgress.class);

        /*  40 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_ServerInfo_VALUE, DemoNetMessages.CSVCMsg_ServerInfo.class);
        /*  41 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_FlattenedSerializer_VALUE, S2NetMessages.CSVCMsg_FlattenedSerializer.class);
        /*  42 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_ClassInfo_VALUE, CommonNetMessages.CSVCMsg_ClassInfo.class);
        /*  44 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_CreateStringTable_VALUE, S2NetMessages.CSVCMsg_CreateStringTable.class);
        /*  45 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_UpdateStringTable_VALUE, CommonNetMessages.CSVCMsg_UpdateStringTable.class);
        /*  46 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_VoiceInit_VALUE, CommonNetMessages.CSVCMsg_VoiceInit.class);
        /*  47 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_VoiceData_VALUE, S2NetMessages.CSVCMsg_VoiceData.class);
        /*  48 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_Print_VALUE, CommonNetMessages.CSVCMsg_Print.class);
        /*  50 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_SetView_VALUE, CommonNetMessages.CSVCMsg_SetView.class);
        /*  51 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_ClearAllStringTables_VALUE, S2NetMessages.CSVCMsg_ClearAllStringTables.class);
        /*  55 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_PacketEntities_VALUE, CommonNetMessages.CSVCMsg_PacketEntities.class);
        /*  60 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_PeerList_VALUE, S2NetMessages.CSVCMsg_PeerList.class);
        /*  62 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_HLTVStatus_VALUE, S2NetMessages.CSVCMsg_HLTVStatus.class);
        /*  70 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_FullFrameSplit_VALUE, CommonNetMessages.CSVCMsg_FullFrameSplit.class);
        /*  76 */ K2C.put(DOTAS2MessageId.SVC_Messages.svc_UserCmds_VALUE, CommonNetMessages.CSVCMsg_UserCommands.class);

        /* 106 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_Fade_VALUE, S2UserMessages.CUserMessageFade.class);
        /* 114 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_RequestState_VALUE, S2UserMessages.CUserMessageRequestState.class);
        /* 115 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_ResetHUD_VALUE, S2UserMessages.CUserMessageResetHUD.class);
        /* 118 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_SayText2_VALUE, S2UserMessages.CUserMessageSayText2.class);
        /* 124 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_TextMsg_VALUE, S2UserMessages.CUserMessageTextMsg.class);
        /* 128 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_VoiceMask_VALUE, S2UserMessages.CUserMessageVoiceMask.class);
        /* 130 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_SendAudio_VALUE, S2UserMessages.CUserMessageSendAudio.class);
        /* 144 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_AudioParameter_VALUE, S2UserMessages.CUserMessageAudioParameter.class);
        /* 145 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_ParticleManager_VALUE, DemoUserMessages.CUserMsg_ParticleManager.class);
        /* 154 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_ServerFrameTime_VALUE, S2UserMessages.CUserMessageServerFrameTime.class);

//      /* 101 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_AchievementEvent_VALUE, S2UserMessages.CUserMessageAchievementEvent.class);
//      /* 102 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CloseCaption_VALUE, S2UserMessages.CUserMessageCloseCaption.class);
//      /* 103 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CloseCaptionDirect_VALUE, S2UserMessages.CUserMessageCloseCaptionDirect.class);
//      /* 104 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CurrentTimescale_VALUE, S2UserMessages.CUserMessageCurrentTimescale.class);
//      /* 105 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_DesiredTimescale_VALUE, S2UserMessages.CUserMessageDesiredTimescale.class);
//      /* 107 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_GameTitle_VALUE, S2UserMessages.CUserMessageGameTitle.class);
//      /* 109 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_HintText_VALUE, S2UserMessages.CUserMessageHintText.class);
//      /* 110 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_HudMsg_VALUE, S2UserMessages.CUserMessageHudMsg.class);
//      /* 111 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_HudText_VALUE, S2UserMessages.CUserMessageHudText.class);
//      /* 112 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_KeyHintText_VALUE, S2UserMessages.CUserMessageKeyHintText.class);
//      /* 113 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_ColoredText_VALUE, S2UserMessages.CUserMessageColoredText.class);
//      /* 116 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_Rumble_VALUE, S2UserMessages.CUserMessageRumble.class);
//      /* 117 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_SayText_VALUE, S2UserMessages.CUserMessageSayText.class);
//      /* 119 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_SayTextChannel_VALUE, S2UserMessages.CUserMessageSayTextChannel.class);
//      /* 120 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_Shake_VALUE, S2UserMessages.CUserMessageShake.class);
//      /* 121 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_ShakeDir_VALUE, S2UserMessages.CUserMessageShakeDir.class);
//      /* 125 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_ScreenTilt_VALUE, S2UserMessages.CUserMessageScreenTilt.class);
//      /* 126 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_Train_VALUE, S2UserMessages.CUserMessageTrain.class);
//      /* 127 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_VGUIMenu_VALUE, S2UserMessages.CUserMessageVGUIMenu.class);
//      /* 129 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_VoiceSubtitle_VALUE, S2UserMessages.CUserMessageVoiceSubtitle.class);
//      /* 131 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_ItemPickup_VALUE, S2UserMessages.CUserMessageItemPickup.class);
//      /* 132 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_AmmoDenied_VALUE, S2UserMessages.CUserMessageAmmoDenied.class);
//      /* 133 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CrosshairAngle_VALUE, S2UserMessages.CUserMessageCrosshairAngle.class);
//      /* 134 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_ShowMenu_VALUE, S2UserMessages.CUserMessageShowMenu.class);
//      /* 135 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CreditsMsg_VALUE, S2UserMessages.CUserMessageCreditsMsg.class);

//      /* 142 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CloseCaptionPlaceholder_VALUE, S2UserMessages.CUserMessageCloseCaptionPlaceholder.class);        System.out.println(K2C.);

//      /* 143 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CameraTransition_VALUE, S2UserMessages.CUserMessageCameraTransition.class);
//      /* 148 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CustomGameEvent_VALUE, null);
//      /* 149 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_AnimGraphUpdate_VALUE, null);
//      /* 150 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_HapticsManagerPulse_VALUE, null);
//      /* 151 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_HapticsManagerEffect_VALUE, null);
//      /* 152 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_CommandQueueState_VALUE, null);
//      /* 153 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_UpdateCssClasses_VALUE, null);
//      /* 155 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_LagCompensationError_VALUE, null);
//      /* 156 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_RequestDllStatus_VALUE, null);
//      /* 154 */ K2C.put(DOTAS2MessageId.EBaseUserMessages.UM_RequestUtilAction_VALUE, null);

        /* 205 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_Source1LegacyGameEventList_VALUE, CommonNetMessages.CSVCMsg_GameEventList.class);
        /* 206 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_Source1LegacyListenEvents_VALUE, S2GameEvents.CMsgSource1LegacyListenEvents.class);
        /* 207 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_Source1LegacyGameEvent_VALUE, CommonNetworkBaseTypes.CSVCMsg_GameEvent.class);
        /* 208 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_SosStartSoundEvent_VALUE, S2GameEvents.CMsgSosStartSoundEvent.class);
        /* 209 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_SosStopSoundEvent_VALUE, S2GameEvents.CMsgSosStopSoundEvent.class);
        /* 210 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_SosSetSoundEventParams_VALUE, S2GameEvents.CMsgSosSetSoundEventParams.class);
        /* 212 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_SosStopSoundEventHash_VALUE, S2GameEvents.CMsgSosStopSoundEventHash.class);

//      /* 200 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_VDebugGameSessionIDEvent_VALUE, S2GameEvents.CMsgVDebugGameSessionIDEvent.class);
//      /* 201 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_PlaceDecalEvent_VALUE, S2GameEvents.CMsgPlaceDecalEvent.class);
//      /* 202 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_ClearWorldDecalsEvent_VALUE, S2GameEvents.CMsgClearWorldDecalsEvent.class);
//      /* 203 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_ClearEntityDecalsEvent_VALUE, S2GameEvents.CMsgClearEntityDecalsEvent.class);
//      /* 204 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_ClearDecalsForSkeletonInstanceEvent_VALUE, S2GameEvents.CMsgClearDecalsForSkeletonInstanceEvent.class);
//      /* 211 */ K2C.put(S2GameEvents.EBaseGameEvents.GE_SosSetLibraryStackFields_VALUE, S2GameEvents.CMsgSosSetLibraryStackFields.class);

        /* 400 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_EffectDispatchId_VALUE, S2TempEntities.CMsgTEEffectDispatch.class);
        /* 401 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_ArmorRicochetId_VALUE, S2TempEntities.CMsgTEArmorRicochet.class);
        /* 402 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BeamEntPointId_VALUE, S2TempEntities.CMsgTEBeamEntPoint.class);
        /* 403 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BeamEntsId_VALUE, S2TempEntities.CMsgTEBeamEnts.class);
        /* 404 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BeamPointsId_VALUE, S2TempEntities.CMsgTEBeamPoints.class);
        /* 405 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BeamRingId_VALUE, S2TempEntities.CMsgTEBeamRing.class);
        /* 406 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BreakModelId_VALUE, S2TempEntities.CMsgTEBreakModel.class);
        /* 407 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BSPDecalId_VALUE, S2TempEntities.CMsgTEBSPDecal.class);
        /* 408 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BubblesId_VALUE, S2TempEntities.CMsgTEBubbles.class);
        /* 409 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BubbleTrailId_VALUE, S2TempEntities.CMsgTEBubbleTrail.class);
        /* 410 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_DecalId_VALUE, S2TempEntities.CMsgTEDecal.class);
        /* 411 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_WorldDecalId_VALUE, S2TempEntities.CMsgTEWorldDecal.class);
        /* 412 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_EnergySplashId_VALUE, S2TempEntities.CMsgTEEnergySplash.class);
        /* 413 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_FizzId_VALUE, S2TempEntities.CMsgTEFizz.class);
        /* 414 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_ShatterSurfaceId_VALUE, S2TempEntities.CMsgTEShatterSurface.class);
        /* 415 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_GlowSpriteId_VALUE, S2TempEntities.CMsgTEGlowSprite.class);
        /* 416 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_ImpactId_VALUE, S2TempEntities.CMsgTEImpact.class);
        /* 417 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_MuzzleFlashId_VALUE, S2TempEntities.CMsgTEMuzzleFlash.class);
        /* 418 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_BloodStreamId_VALUE, S2TempEntities.CMsgTEBloodStream.class);
        /* 419 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_ExplosionId_VALUE, S2TempEntities.CMsgTEExplosion.class);
        /* 420 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_DustId_VALUE, S2TempEntities.CMsgTEDust.class);
        /* 421 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_LargeFunnelId_VALUE, S2TempEntities.CMsgTELargeFunnel.class);
        /* 422 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_SparksId_VALUE, S2TempEntities.CMsgTESparks.class);
        /* 423 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_PhysicsPropId_VALUE, S2TempEntities.CMsgTEPhysicsProp.class);
        /* 424 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_PlayerDecalId_VALUE, S2TempEntities.CMsgTEPlayerDecal.class);
        /* 425 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_ProjectedDecalId_VALUE, S2TempEntities.CMsgTEProjectedDecal.class);
        /* 426 */ K2C.put(S2TempEntities.ETEProtobufIds.TE_SmokeId_VALUE, S2TempEntities.CMsgTESmoke.class);

        /* 466 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ChatEvent_VALUE, DOTAUserMessages.CDOTAUserMsg_ChatEvent.class);
        /* 470 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CombatLogBulkData_VALUE, DOTAUserMessages.CDOTAUserMsg_CombatLogBulkData.class);
        /* 471 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CreateLinearProjectile_VALUE, DOTAUserMessages.CDOTAUserMsg_CreateLinearProjectile.class);
        /* 472 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_DestroyLinearProjectile_VALUE, DOTAUserMessages.CDOTAUserMsg_DestroyLinearProjectile.class);
        /* 474 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_GlobalLightColor_VALUE, DOTAUserMessages.CDOTAUserMsg_GlobalLightColor.class);
        /* 475 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_GlobalLightDirection_VALUE, DOTAUserMessages.CDOTAUserMsg_GlobalLightDirection.class);
        /* 473 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_DodgeTrackingProjectiles_VALUE, DOTAUserMessages.CDOTAUserMsg_DodgeTrackingProjectiles.class);
        /* 477 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_LocationPing_VALUE, DOTAUserMessages.CDOTAUserMsg_LocationPing.class);
        /* 478 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MapLine_VALUE, DOTAUserMessages.CDOTAUserMsg_MapLine.class);
        /* 479 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MiniKillCamInfo_VALUE, DOTAUserMessages.CDOTAUserMsg_MiniKillCamInfo.class);
        /* 481 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MinimapEvent_VALUE, DOTAUserMessages.CDOTAUserMsg_MinimapEvent.class);
        /* 482 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_NevermoreRequiem_VALUE, DOTAUserMessages.CDOTAUserMsg_NevermoreRequiem.class);
        /* 483 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_OverheadEvent_VALUE, DOTAUserMessages.CDOTAUserMsg_OverheadEvent.class);
        /* 485 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SharedCooldown_VALUE, DOTAUserMessages.CDOTAUserMsg_SharedCooldown.class);
        /* 486 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SpectatorPlayerClick_VALUE, DOTAUserMessages.CDOTAUserMsg_SpectatorPlayerClick.class);
        /* 488 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_UnitEvent_VALUE, DOTAUserMessages.CDOTAUserMsg_UnitEvent.class);
        /* 489 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ParticleManager_VALUE, DemoUserMessages.CUserMsg_ParticleManager.class);
        /* 490 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_BotChat_VALUE, DOTAUserMessages.CDOTAUserMsg_BotChat.class);
        /* 491 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_HudError_VALUE, DOTAUserMessages.CDOTAUserMsg_HudError.class);
        /* 492 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ItemPurchased_VALUE, DOTAUserMessages.CDOTAUserMsg_ItemPurchased.class);
        /* 496 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SwapVerify_VALUE, DOTAUserMessages.CDOTAUserMsg_SwapVerify.class);
        /* 497 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_WorldLine_VALUE, DOTAUserMessages.CDOTAUserMsg_WorldLine.class);
        /* 499 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ItemAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_ItemAlert.class);
        /* 501 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ChatWheel_VALUE, DOTAUserMessages.CDOTAUserMsg_ChatWheel.class);
        /* 506 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_GamerulesStateChanged_VALUE, DOTAUserMessages.CDOTAUserMsg_GamerulesStateChanged.class);
        /* 510 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SendStatPopup_VALUE, DOTAUserMessages.CDOTAUserMsg_SendStatPopup.class);
        /* 512 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SendRoshanPopup_VALUE, DOTAUserMessages.CDOTAUserMsg_SendRoshanPopup.class);
        /* 518 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TE_Projectile_VALUE, DOTAUserMessages.CDOTAUserMsg_TE_Projectile.class);
        /* 519 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TE_ProjectileLoc_VALUE, DOTAUserMessages.CDOTAUserMsg_TE_ProjectileLoc.class);
        /* 520 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TE_DotaBloodImpact_VALUE, DOTAUserMessages.CDOTAUserMsg_TE_DotaBloodImpact.class);
        /* 521 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TE_UnitAnimation_VALUE, DOTAUserMessages.CDOTAUserMsg_TE_UnitAnimation.class);
        /* 522 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TE_UnitAnimationEnd_VALUE, DOTAUserMessages.CDOTAUserMsg_TE_UnitAnimationEnd.class);
        /* 523 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_AbilityPing_VALUE, DOTAUserMessages.CDOTAUserMsg_AbilityPing.class);
        /* 529 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_WillPurchaseAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_WillPurchaseAlert.class);
        /* 531 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_PlayerMMR_VALUE, DOTAUserMessages.CDOTAUserMsg_PlayerMMR.class);
        /* 532 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_AbilitySteal_VALUE, DOTAUserMessages.CDOTAUserMsg_AbilitySteal.class);
        /* 533 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CourierKilledAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_CourierKilledAlert.class);
        /* 534 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_EnemyItemAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_EnemyItemAlert.class);
        /* 537 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_BuyBackStateAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_BuyBackStateAlert.class);
        /* 540 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_QuickBuyAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_QuickBuyAlert.class);
        /* 542 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_PredictionResult_VALUE, DOTAUserMessages.CDOTAUserMsg_PredictionResult.class);
        /* 543 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ModifierAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_ModifierAlert.class);
        /* 544 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_HPManaAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_HPManaAlert.class);
        /* 547 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SpectatorPlayerUnitOrders_VALUE, DOTAUserMessages.CDOTAUserMsg_SpectatorPlayerUnitOrders.class);
        /* 552 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ProjectionAbility_VALUE, DOTAUserMessages.CDOTAUserMsg_ProjectionAbility.class);
        /* 553 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ProjectionEvent_VALUE, DOTAUserMessages.CDOTAUserMsg_ProjectionEvent.class);
        /* 554 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CombatLogDataHLTV_VALUE, DOTAUserMessages.CMsgDOTACombatLogEntry.class);
        /* 555 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_XPAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_XPAlert.class);
        /* 556 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_UpdateQuestProgress_VALUE, DOTAUserMessages.CDOTAUserMsg_UpdateQuestProgress.class);
        /* 557 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MatchMetadata_VALUE, DOTAS2MatchMetadata.CDOTAMatchMetadataFile.class);
        /* 558 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MatchDetails_VALUE, DOTAS2GcMessagesCommon.CMsgDOTAMatch.class);
        /* 562 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_KillcamDamageTaken_VALUE, DOTAUserMessages.CDOTAUserMsg_KillcamDamageTaken.class);
        /* 563 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SelectPenaltyGold_VALUE, DOTAUserMessages.CDOTAUserMsg_SelectPenaltyGold.class);
        /* 564 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_RollDiceResult_VALUE, DOTAUserMessages.CDOTAUserMsg_RollDiceResult.class);
        /* 565 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_FlipCoinResult_VALUE, DOTAUserMessages.CDOTAUserMsg_FlipCoinResult.class);
        /* 567 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TeamCaptainChanged_VALUE, DOTAUserMessages.CDOTAUserMessage_TeamCaptainChanged.class);
        /* 568 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SendRoshanSpectatorPhase_VALUE, DOTAUserMessages.CDOTAUserMsg_SendRoshanSpectatorPhase.class);
        /* 571 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TE_DestroyProjectile_VALUE, DOTAUserMessages.CDOTAUserMsg_TE_DestroyProjectile.class);
        /* 572 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_HeroRelicProgress_VALUE, DOTAUserMessages.CDOTAUserMsg_HeroRelicProgress.class);
        /* 574 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ItemSold_VALUE, DOTAUserMessages.CDOTAUserMsg_ItemSold.class);
        /* 575 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_DamageReport_VALUE, DOTAUserMessages.CDOTAUserMsg_DamageReport.class);
        /* 576 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SalutePlayer_VALUE, DOTAUserMessages.CDOTAUserMsg_SalutePlayer.class);
        /* 577 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TipAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_TipAlert.class);
        /* 579 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_EmptyTeleportAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_EmptyTeleportAlert.class);
        /* 580 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MarsArenaOfBloodAttack_VALUE, DOTAUserMessages.CDOTAUserMsg_MarsArenaOfBloodAttack.class);
        /* 581 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ESArcanaCombo_VALUE, DOTAUserMessages.CDOTAUserMsg_ESArcanaCombo.class);
        /* 582 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ESArcanaComboSummary_VALUE, DOTAUserMessages.CDOTAUserMsg_ESArcanaComboSummary.class);
        /* 583 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_HighFiveLeftHanging_VALUE, DOTAUserMessages.CDOTAUserMsg_HighFiveLeftHanging.class);
        /* 584 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_HighFiveCompleted_VALUE, DOTAUserMessages.CDOTAUserMsg_HighFiveCompleted.class);
        /* 585 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ShovelUnearth_VALUE, DOTAUserMessages.CDOTAUserMsg_ShovelUnearth.class);
        /* 586 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_EM_InvokerSpellCast_VALUE, DOTAUserMessages.CDOTAEntityMsg_InvokerSpellCast.class);
        /* 587 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_RadarAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_RadarAlert.class);
        /* 588 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_AllStarEvent_VALUE, DOTAUserMessages.CDOTAUserMsg_AllStarEvent.class);
        /* 589 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TalentTreeAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_TalentTreeAlert.class);
        /* 590 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_QueuedOrderRemoved_VALUE, DOTAUserMessages.CDOTAUserMsg_QueuedOrderRemoved.class);
        /* 591 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_DebugChallenge_VALUE, DOTAUserMessages.CDOTAUserMsg_DebugChallenge.class);
        /* 592 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_OMArcanaCombo_VALUE, DOTAUserMessages.CDOTAUserMsg_OMArcanaCombo.class);
        /* 593 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_FoundNeutralItem_VALUE, DOTAUserMessages.CDOTAUserMsg_FoundNeutralItem.class);
        /* 594 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_OutpostCaptured_VALUE, DOTAUserMessages.CDOTAUserMsg_OutpostCaptured.class);
        /* 595 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_OutpostGrantedXP_VALUE, DOTAUserMessages.CDOTAUserMsg_OutpostGrantedXP.class);
        /* 596 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MoveCameraToUnit_VALUE, DOTAUserMessages.CDOTAUserMsg_MoveCameraToUnit.class);
        /* 597 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_PauseMinigameData_VALUE, DOTAUserMessages.CDOTAUserMsg_PauseMinigameData.class);
        /* 598 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_VersusScene_PlayerBehavior_VALUE, DOTAUserMessages.CDOTAUserMsg_VersusScene_PlayerBehavior.class);
        /* 600 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_QoP_ArcanaSummary_VALUE, DOTAUserMessages.CDOTAUserMsg_QoP_ArcanaSummary.class);
        /* 601 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_HotPotato_Created_VALUE, DOTAUserMessages.CDOTAUserMsg_HotPotato_Created.class);
        /* 602 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_HotPotato_Exploded_VALUE, DOTAUserMessages.CDOTAUserMsg_HotPotato_Exploded.class);
        /* 603 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_WK_Arcana_Progress_VALUE, DOTAUserMessages.CDOTAUserMsg_WK_Arcana_Progress.class);
        /* 604 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_GuildChallenge_Progress_VALUE, DOTAUserMessages.CDOTAUserMsg_GuildChallenge_Progress.class);
        /* 605 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_WRArcanaProgress_VALUE, DOTAUserMessages.CDOTAUserMsg_WRArcanaProgress.class);
        /* 606 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_WRArcanaSummary_VALUE, DOTAUserMessages.CDOTAUserMsg_WRArcanaSummary.class);
        /* 607 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_EmptyItemSlotAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_EmptyItemSlotAlert.class);
        /* 608 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_AghsStatusAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_AghsStatusAlert.class);
        /* 610 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MutedPlayers_VALUE, DOTAUserMessages.CDOTAUserMsg_MutedPlayers.class);
        /* 611 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ContextualTip_VALUE, DOTAUserMessages.CDOTAUserMsg_ContextualTip.class);
        /* 612 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ChatMessage_VALUE, DOTAUserMessages.CDOTAUserMsg_ChatMessage.class);
        /* 616 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_DuelOpponentKilled_VALUE, DOTAUserMessages.CDOTAUserMsg_DuelOpponentKilled.class);
        /* 617 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_DuelAccepted_VALUE, DOTAUserMessages.CDOTAUserMsg_DuelAccepted.class);
        /* 619 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MuertaReleaseEvent_AssignedTargetKilled_VALUE, DOTAUserMessages.CDOTAUserMsg_MuertaReleaseEvent_AssignedTargetKilled.class);
        /* 620 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_PlayerDraftSuggestPick_VALUE, DOTAUserMessages.CDOTAUserMsg_PlayerDraftSuggestPick.class);
        /* 621 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_PlayerDraftPick_VALUE, DOTAUserMessages.CDOTAUserMsg_PlayerDraftPick.class);
        /* 622 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_UpdateLinearProjectileCPData_VALUE, DOTAUserMessages.CDOTAUserMsg_ProjectileParticleCPData.class);
        /* 623 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_GiftPlayer_VALUE, DOTAUserMessages.CDOTAUserMsg_GiftPlayer.class);
        /* 624 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_FacetPing_VALUE, DOTAUserMessages.CDOTAUserMsg_FacetPing.class);

//      /* 464 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_AddUnitToSelection_VALUE, null);
//      /* 465 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_AIDebugLine_VALUE, DOTAUserMessages.CDOTAUserMsg_AIDebugLine.class);
//      /* 467 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CombatHeroPositions_VALUE, DOTAUserMessages.CDOTAUserMsg_CombatHeroPositions.class);
//      /* 468 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CombatLogData_VALUE, null);
//      /* 476 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_InvalidCommand_VALUE, DOTAUserMessages.CDOTAUserMsg_InvalidCommand.class);
//      /* 480 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MinimapDebugPoint_VALUE, DOTAUserMessages.CDOTAUserMsg_MinimapDebugPoint.class);
//      /* 484 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SetNextAutobuyItem_VALUE, DOTAUserMessages.CDOTAUserMsg_SetNextAutobuyItem.class);
//      /* 487 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TutorialTipInfo_VALUE, DOTAUserMessages.CDOTAUserMsg_TutorialTipInfo.class);
//      /* 493 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_Ping_VALUE, DOTAUserMessages.CDOTAUserMsg_Ping.class);
//      /* 494 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ItemFound_VALUE, DOTAUserMessages.CDOTAUserMsg_ItemFound.class);
//      /* 495 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CharacterSpeakConcept_VALUE, null);
//      /* 498 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TournamentDrop_VALUE, null);
//      /* 500 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_HalloweenDrops_VALUE, DOTAUserMessages.CDOTAUserMsg_HalloweenDrops.class);
//      /* 502 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ReceivedXmasGift_VALUE, DOTAUserMessages.CDOTAUserMsg_ReceivedXmasGift.class);
//      /* 503 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_UpdateSharedContent_VALUE, DOTAUserMessages.CDOTAUserMsg_UpdateSharedContent.class);
//      /* 504 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TutorialRequestExp_VALUE, DOTAUserMessages.CDOTAUserMsg_TutorialRequestExp.class);
//      /* 505 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TutorialPingMinimap_VALUE, DOTAUserMessages.CDOTAUserMsg_TutorialPingMinimap.class);
//      /* 507 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ShowSurvey_VALUE, DOTAUserMessages.CDOTAUserMsg_ShowSurvey.class);
//      /* 508 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TutorialFade_VALUE, DOTAUserMessages.CDOTAUserMsg_TutorialFade.class);
//      /* 509 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_AddQuestLogEntry_VALUE, DOTAUserMessages.CDOTAUserMsg_AddQuestLogEntry.class);
//      /* 511 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TutorialFinish_VALUE, DOTAUserMessages.CDOTAUserMsg_TutorialFinish.class);
//      /* 513 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SendGenericToolTip_VALUE, DOTAUserMessages.CDOTAUserMsg_SendGenericToolTip.class);
//      /* 514 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SendFinalGold_VALUE, DOTAUserMessages.CDOTAUserMsg_SendFinalGold.class);
//      /* 515 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CustomMsg_VALUE, DOTAUserMessages.CDOTAUserMsg_CustomMsg.class);
//      /* 516 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CoachHUDPing_VALUE, DOTAUserMessages.CDOTAUserMsg_CoachHUDPing.class);
//      /* 517 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ClientLoadGridNav_VALUE, DOTAUserMessages.CDOTAUserMsg_ClientLoadGridNav.class);
//      /* 524 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ShowGenericPopup_VALUE, DOTAUserMessages.CDOTAUserMsg_ShowGenericPopup.class);
//      /* 525 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_VoteStart_VALUE, DOTAUserMessages.CDOTAUserMsg_VoteStart.class);
//      /* 526 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_VoteUpdate_VALUE, DOTAUserMessages.CDOTAUserMsg_VoteUpdate.class);
//      /* 527 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_VoteEnd_VALUE, DOTAUserMessages.CDOTAUserMsg_VoteEnd.class);
//      /* 528 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_BoosterState_VALUE, DOTAUserMessages.CDOTAUserMsg_BoosterState.class);
//      /* 530 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_TutorialMinimapPosition_VALUE, DOTAUserMessages.CDOTAUserMsg_TutorialMinimapPosition.class);
//      /* 531 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_PlayerMMR_VALUE, DOTAUserMessages.CDOTAUserMsg_PlayerMMR.class);
//      /* 535 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_StatsMatchDetails_VALUE, DOTAUserMessages.CDOTAUserMsg_StatsMatchDetails.class);
//      /* 536 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_MiniTaunt_VALUE, DOTAUserMessages.CDOTAUserMsg_MiniTaunt.class);
//      /* 538 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SpeechBubble_VALUE, DOTAUserMessages.CDOTAUserMsg_SpeechBubble.class);
//      /* 539 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CustomHeaderMessage_VALUE, DOTAUserMessages.CDOTAUserMsg_CustomHeaderMessage.class);
//      /* 541 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_StatsHeroDetails_VALUE, DOTAUserMessages.CDOTAUserMsg_StatsHeroMinuteDetails.class);
//      /* 545 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_GlyphAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_GlyphAlert.class);
//      /* 546 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_BeastChat_VALUE, DOTAUserMessages.CDOTAUserMsg_BeastChat.class);
//      /* 548 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CustomHudElement_Create_VALUE, DOTAUserMessages.CDOTAUserMsg_CustomHudElement_Create.class);
//      /* 549 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CustomHudElement_Modify_VALUE, DOTAUserMessages.CDOTAUserMsg_CustomHudElement_Modify.class);
//      /* 550 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CustomHudElement_Destroy_VALUE, DOTAUserMessages.CDOTAUserMsg_CustomHudElement_Destroy.class);
//      /* 551 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_CompendiumState_VALUE, DOTAUserMessages.CDOTAUserMsg_CompendiumState.class);
//      /* 559 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_QuestStatus_VALUE, DOTAUserMessages.CDOTAUserMsg_QuestStatus.class);
//      /* 560 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SuggestHeroPick_VALUE, DOTAUserMessages.CDOTAUserMsg_SuggestHeroPick.class);
//      /* 561 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_SuggestHeroRole_VALUE, DOTAUserMessages.CDOTAUserMsg_SuggestHeroRole.class);
//      /* 562 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_KillcamDamageTaken_VALUE, DOTAUserMessages.CDOTAUserMsg_KillcamDamageTaken.class);
//      /* 566 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_RequestItemSuggestions_VALUE, DOTAUserMessages.CDOTAUserMessage_RequestItemSuggestions.class);
//      /* 569 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ChatWheelCooldown_VALUE, DOTAUserMessages.CDOTAUserMessage_ChatWheelCooldown.class);
//      /* 570 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_DismissAllStatPopups_VALUE, DOTAUserMessages.CDOTAUserMessage_DismissAllStatPopups.class);
//      /* 573 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_AbilityDraftRequestAbility_VALUE, DOTAUserMessages.CDOTAUserMessage_AbilityDraftRequestAbility.class);
//      /* 578 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ReplaceQueryUnit_VALUE, DOTAUserMessages.CDOTAUserMsg_ReplaceQueryUnit.class);
//      /* 579 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_EmptyTeleportAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_EmptyTeleportAlert.class);
//      /* 609 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_PingConfirmation_VALUE, DOTAUserMessages.CDOTAUserMsg_PingConfirmation.class);
//      /* 611 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ContextualTip_VALUE, DOTAUserMessages.CDOTAUserMsg_ContextualTip.class);
//      /* 612 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_ChatMessage_VALUE, DOTAUserMessages.CDOTAUserMsg_ChatMessage.class);
//      /* 613 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_NeutralCampAlert_VALUE, DOTAUserMessages.CDOTAUserMsg_NeutralCampAlert.class);
//      /* 614 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_RockPaperScissorsStarted_VALUE, DOTAUserMessages.CDOTAUserMsg_RockPaperScissorsStarted.class);
//      /* 615 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_RockPaperScissorsFinished_VALUE, DOTAUserMessages.CDOTAUserMsg_RockPaperScissorsFinished.class);
//      /* 618 */ K2C.put(DOTAS2MessageId.EDotaUserMessages.DOTA_UM_DuelRequested_VALUE, DOTAUserMessages.CDOTAUserMsg_DuelRequested.class);
    }

    public static Class<? extends GeneratedMessage> classForKind(int kind) {
        return K2C.classForKind(kind);
    }

    private static ClassToKindMessageRegistry C2K;

    public static Integer kindForClass(Class<? extends GeneratedMessage> clazz) {
        if (C2K == null) {
            C2K = K2C.buildReverse();
        }
        return C2K.kindForClass(clazz);
    }

}
