// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: claritymessages.proto

package skadistats.clarity.wire.cs.csgo.proto;

public final class CsgoClarityMessages {
  private CsgoClarityMessages() {}
  public static void registerAllExtensions(
      skadistats.clarity.protobuf.ExtensionRegistry registry) {
  }
  public interface CsgoDemoHeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CsgoDemoHeader)
      skadistats.clarity.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 demoprotocol = 1;</code>
     *
     * <pre>
     * Should be DEMO_PROTOCOL
     * </pre>
     */
    boolean hasDemoprotocol();
    /**
     * <code>optional int32 demoprotocol = 1;</code>
     *
     * <pre>
     * Should be DEMO_PROTOCOL
     * </pre>
     */
    int getDemoprotocol();

    /**
     * <code>optional int32 networkprotocol = 2;</code>
     *
     * <pre>
     * Should be PROTOCOL_VERSION
     * </pre>
     */
    boolean hasNetworkprotocol();
    /**
     * <code>optional int32 networkprotocol = 2;</code>
     *
     * <pre>
     * Should be PROTOCOL_VERSION
     * </pre>
     */
    int getNetworkprotocol();

    /**
     * <code>optional string servername = 3;</code>
     *
     * <pre>
     * Name of server
     * </pre>
     */
    boolean hasServername();
    /**
     * <code>optional string servername = 3;</code>
     *
     * <pre>
     * Name of server
     * </pre>
     */
    java.lang.String getServername();
    /**
     * <code>optional string servername = 3;</code>
     *
     * <pre>
     * Name of server
     * </pre>
     */
    skadistats.clarity.protobuf.ByteString
        getServernameBytes();

    /**
     * <code>optional string clientname = 4;</code>
     *
     * <pre>
     * Name of client who recorded the game
     * </pre>
     */
    boolean hasClientname();
    /**
     * <code>optional string clientname = 4;</code>
     *
     * <pre>
     * Name of client who recorded the game
     * </pre>
     */
    java.lang.String getClientname();
    /**
     * <code>optional string clientname = 4;</code>
     *
     * <pre>
     * Name of client who recorded the game
     * </pre>
     */
    skadistats.clarity.protobuf.ByteString
        getClientnameBytes();

    /**
     * <code>optional string mapname = 5;</code>
     *
     * <pre>
     * Name of map
     * </pre>
     */
    boolean hasMapname();
    /**
     * <code>optional string mapname = 5;</code>
     *
     * <pre>
     * Name of map
     * </pre>
     */
    java.lang.String getMapname();
    /**
     * <code>optional string mapname = 5;</code>
     *
     * <pre>
     * Name of map
     * </pre>
     */
    skadistats.clarity.protobuf.ByteString
        getMapnameBytes();

    /**
     * <code>optional string gamedirectory = 6;</code>
     *
     * <pre>
     * Name of game directory (com_gamedir)
     * </pre>
     */
    boolean hasGamedirectory();
    /**
     * <code>optional string gamedirectory = 6;</code>
     *
     * <pre>
     * Name of game directory (com_gamedir)
     * </pre>
     */
    java.lang.String getGamedirectory();
    /**
     * <code>optional string gamedirectory = 6;</code>
     *
     * <pre>
     * Name of game directory (com_gamedir)
     * </pre>
     */
    skadistats.clarity.protobuf.ByteString
        getGamedirectoryBytes();

    /**
     * <code>optional float playback_time = 7;</code>
     *
     * <pre>
     * Time of track
     * </pre>
     */
    boolean hasPlaybackTime();
    /**
     * <code>optional float playback_time = 7;</code>
     *
     * <pre>
     * Time of track
     * </pre>
     */
    float getPlaybackTime();

    /**
     * <code>optional int32 playback_ticks = 8;</code>
     *
     * <pre>
     * # of ticks in track
     * </pre>
     */
    boolean hasPlaybackTicks();
    /**
     * <code>optional int32 playback_ticks = 8;</code>
     *
     * <pre>
     * # of ticks in track
     * </pre>
     */
    int getPlaybackTicks();

    /**
     * <code>optional int32 playback_frames = 9;</code>
     *
     * <pre>
     * # of frames in track
     * </pre>
     */
    boolean hasPlaybackFrames();
    /**
     * <code>optional int32 playback_frames = 9;</code>
     *
     * <pre>
     * # of frames in track
     * </pre>
     */
    int getPlaybackFrames();

    /**
     * <code>optional int32 signonlength = 10;</code>
     *
     * <pre>
     * length of sigondata in bytes
     * </pre>
     */
    boolean hasSignonlength();
    /**
     * <code>optional int32 signonlength = 10;</code>
     *
     * <pre>
     * length of sigondata in bytes
     * </pre>
     */
    int getSignonlength();
  }
  /**
   * Protobuf type {@code CsgoDemoHeader}
   */
  public static final class CsgoDemoHeader extends
      skadistats.clarity.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CsgoDemoHeader)
      CsgoDemoHeaderOrBuilder {
    // Use CsgoDemoHeader.newBuilder() to construct.
    private CsgoDemoHeader(skadistats.clarity.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CsgoDemoHeader(boolean noInit) { this.unknownFields = skadistats.clarity.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CsgoDemoHeader defaultInstance;
    public static CsgoDemoHeader getDefaultInstance() {
      return defaultInstance;
    }

    public CsgoDemoHeader getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final skadistats.clarity.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final skadistats.clarity.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CsgoDemoHeader(
        skadistats.clarity.protobuf.CodedInputStream input,
        skadistats.clarity.protobuf.ExtensionRegistryLite extensionRegistry)
        throws skadistats.clarity.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      skadistats.clarity.protobuf.UnknownFieldSet.Builder unknownFields =
          skadistats.clarity.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              demoprotocol_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              networkprotocol_ = input.readInt32();
              break;
            }
            case 26: {
              skadistats.clarity.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              servername_ = bs;
              break;
            }
            case 34: {
              skadistats.clarity.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              clientname_ = bs;
              break;
            }
            case 42: {
              skadistats.clarity.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000010;
              mapname_ = bs;
              break;
            }
            case 50: {
              skadistats.clarity.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              gamedirectory_ = bs;
              break;
            }
            case 61: {
              bitField0_ |= 0x00000040;
              playbackTime_ = input.readFloat();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              playbackTicks_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              playbackFrames_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              signonlength_ = input.readInt32();
              break;
            }
          }
        }
      } catch (skadistats.clarity.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new skadistats.clarity.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final skadistats.clarity.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.internal_static_CsgoDemoHeader_descriptor;
    }

    protected skadistats.clarity.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.internal_static_CsgoDemoHeader_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader.class, skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader.Builder.class);
    }

    public static skadistats.clarity.protobuf.Parser<CsgoDemoHeader> PARSER =
        new skadistats.clarity.protobuf.AbstractParser<CsgoDemoHeader>() {
      public CsgoDemoHeader parsePartialFrom(
          skadistats.clarity.protobuf.CodedInputStream input,
          skadistats.clarity.protobuf.ExtensionRegistryLite extensionRegistry)
          throws skadistats.clarity.protobuf.InvalidProtocolBufferException {
        return new CsgoDemoHeader(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public skadistats.clarity.protobuf.Parser<CsgoDemoHeader> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DEMOPROTOCOL_FIELD_NUMBER = 1;
    private int demoprotocol_;
    /**
     * <code>optional int32 demoprotocol = 1;</code>
     *
     * <pre>
     * Should be DEMO_PROTOCOL
     * </pre>
     */
    public boolean hasDemoprotocol() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 demoprotocol = 1;</code>
     *
     * <pre>
     * Should be DEMO_PROTOCOL
     * </pre>
     */
    public int getDemoprotocol() {
      return demoprotocol_;
    }

    public static final int NETWORKPROTOCOL_FIELD_NUMBER = 2;
    private int networkprotocol_;
    /**
     * <code>optional int32 networkprotocol = 2;</code>
     *
     * <pre>
     * Should be PROTOCOL_VERSION
     * </pre>
     */
    public boolean hasNetworkprotocol() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 networkprotocol = 2;</code>
     *
     * <pre>
     * Should be PROTOCOL_VERSION
     * </pre>
     */
    public int getNetworkprotocol() {
      return networkprotocol_;
    }

    public static final int SERVERNAME_FIELD_NUMBER = 3;
    private java.lang.Object servername_;
    /**
     * <code>optional string servername = 3;</code>
     *
     * <pre>
     * Name of server
     * </pre>
     */
    public boolean hasServername() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string servername = 3;</code>
     *
     * <pre>
     * Name of server
     * </pre>
     */
    public java.lang.String getServername() {
      java.lang.Object ref = servername_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        skadistats.clarity.protobuf.ByteString bs = 
            (skadistats.clarity.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          servername_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string servername = 3;</code>
     *
     * <pre>
     * Name of server
     * </pre>
     */
    public skadistats.clarity.protobuf.ByteString
        getServernameBytes() {
      java.lang.Object ref = servername_;
      if (ref instanceof java.lang.String) {
        skadistats.clarity.protobuf.ByteString b = 
            skadistats.clarity.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        servername_ = b;
        return b;
      } else {
        return (skadistats.clarity.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTNAME_FIELD_NUMBER = 4;
    private java.lang.Object clientname_;
    /**
     * <code>optional string clientname = 4;</code>
     *
     * <pre>
     * Name of client who recorded the game
     * </pre>
     */
    public boolean hasClientname() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string clientname = 4;</code>
     *
     * <pre>
     * Name of client who recorded the game
     * </pre>
     */
    public java.lang.String getClientname() {
      java.lang.Object ref = clientname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        skadistats.clarity.protobuf.ByteString bs = 
            (skadistats.clarity.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string clientname = 4;</code>
     *
     * <pre>
     * Name of client who recorded the game
     * </pre>
     */
    public skadistats.clarity.protobuf.ByteString
        getClientnameBytes() {
      java.lang.Object ref = clientname_;
      if (ref instanceof java.lang.String) {
        skadistats.clarity.protobuf.ByteString b = 
            skadistats.clarity.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientname_ = b;
        return b;
      } else {
        return (skadistats.clarity.protobuf.ByteString) ref;
      }
    }

    public static final int MAPNAME_FIELD_NUMBER = 5;
    private java.lang.Object mapname_;
    /**
     * <code>optional string mapname = 5;</code>
     *
     * <pre>
     * Name of map
     * </pre>
     */
    public boolean hasMapname() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string mapname = 5;</code>
     *
     * <pre>
     * Name of map
     * </pre>
     */
    public java.lang.String getMapname() {
      java.lang.Object ref = mapname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        skadistats.clarity.protobuf.ByteString bs = 
            (skadistats.clarity.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mapname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mapname = 5;</code>
     *
     * <pre>
     * Name of map
     * </pre>
     */
    public skadistats.clarity.protobuf.ByteString
        getMapnameBytes() {
      java.lang.Object ref = mapname_;
      if (ref instanceof java.lang.String) {
        skadistats.clarity.protobuf.ByteString b = 
            skadistats.clarity.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mapname_ = b;
        return b;
      } else {
        return (skadistats.clarity.protobuf.ByteString) ref;
      }
    }

    public static final int GAMEDIRECTORY_FIELD_NUMBER = 6;
    private java.lang.Object gamedirectory_;
    /**
     * <code>optional string gamedirectory = 6;</code>
     *
     * <pre>
     * Name of game directory (com_gamedir)
     * </pre>
     */
    public boolean hasGamedirectory() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string gamedirectory = 6;</code>
     *
     * <pre>
     * Name of game directory (com_gamedir)
     * </pre>
     */
    public java.lang.String getGamedirectory() {
      java.lang.Object ref = gamedirectory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        skadistats.clarity.protobuf.ByteString bs = 
            (skadistats.clarity.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gamedirectory_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string gamedirectory = 6;</code>
     *
     * <pre>
     * Name of game directory (com_gamedir)
     * </pre>
     */
    public skadistats.clarity.protobuf.ByteString
        getGamedirectoryBytes() {
      java.lang.Object ref = gamedirectory_;
      if (ref instanceof java.lang.String) {
        skadistats.clarity.protobuf.ByteString b = 
            skadistats.clarity.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gamedirectory_ = b;
        return b;
      } else {
        return (skadistats.clarity.protobuf.ByteString) ref;
      }
    }

    public static final int PLAYBACK_TIME_FIELD_NUMBER = 7;
    private float playbackTime_;
    /**
     * <code>optional float playback_time = 7;</code>
     *
     * <pre>
     * Time of track
     * </pre>
     */
    public boolean hasPlaybackTime() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional float playback_time = 7;</code>
     *
     * <pre>
     * Time of track
     * </pre>
     */
    public float getPlaybackTime() {
      return playbackTime_;
    }

    public static final int PLAYBACK_TICKS_FIELD_NUMBER = 8;
    private int playbackTicks_;
    /**
     * <code>optional int32 playback_ticks = 8;</code>
     *
     * <pre>
     * # of ticks in track
     * </pre>
     */
    public boolean hasPlaybackTicks() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int32 playback_ticks = 8;</code>
     *
     * <pre>
     * # of ticks in track
     * </pre>
     */
    public int getPlaybackTicks() {
      return playbackTicks_;
    }

    public static final int PLAYBACK_FRAMES_FIELD_NUMBER = 9;
    private int playbackFrames_;
    /**
     * <code>optional int32 playback_frames = 9;</code>
     *
     * <pre>
     * # of frames in track
     * </pre>
     */
    public boolean hasPlaybackFrames() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional int32 playback_frames = 9;</code>
     *
     * <pre>
     * # of frames in track
     * </pre>
     */
    public int getPlaybackFrames() {
      return playbackFrames_;
    }

    public static final int SIGNONLENGTH_FIELD_NUMBER = 10;
    private int signonlength_;
    /**
     * <code>optional int32 signonlength = 10;</code>
     *
     * <pre>
     * length of sigondata in bytes
     * </pre>
     */
    public boolean hasSignonlength() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional int32 signonlength = 10;</code>
     *
     * <pre>
     * length of sigondata in bytes
     * </pre>
     */
    public int getSignonlength() {
      return signonlength_;
    }

    private void initFields() {
      demoprotocol_ = 0;
      networkprotocol_ = 0;
      servername_ = "";
      clientname_ = "";
      mapname_ = "";
      gamedirectory_ = "";
      playbackTime_ = 0F;
      playbackTicks_ = 0;
      playbackFrames_ = 0;
      signonlength_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(skadistats.clarity.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, demoprotocol_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, networkprotocol_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getServernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getClientnameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getMapnameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getGamedirectoryBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeFloat(7, playbackTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, playbackTicks_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, playbackFrames_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, signonlength_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeInt32Size(1, demoprotocol_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeInt32Size(2, networkprotocol_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeBytesSize(3, getServernameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeBytesSize(4, getClientnameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeBytesSize(5, getMapnameBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeBytesSize(6, getGamedirectoryBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeFloatSize(7, playbackTime_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeInt32Size(8, playbackTicks_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeInt32Size(9, playbackFrames_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += skadistats.clarity.protobuf.CodedOutputStream
          .computeInt32Size(10, signonlength_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseFrom(
        skadistats.clarity.protobuf.ByteString data)
        throws skadistats.clarity.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseFrom(
        skadistats.clarity.protobuf.ByteString data,
        skadistats.clarity.protobuf.ExtensionRegistryLite extensionRegistry)
        throws skadistats.clarity.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseFrom(byte[] data)
        throws skadistats.clarity.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseFrom(
        byte[] data,
        skadistats.clarity.protobuf.ExtensionRegistryLite extensionRegistry)
        throws skadistats.clarity.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseFrom(
        java.io.InputStream input,
        skadistats.clarity.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseDelimitedFrom(
        java.io.InputStream input,
        skadistats.clarity.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseFrom(
        skadistats.clarity.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parseFrom(
        skadistats.clarity.protobuf.CodedInputStream input,
        skadistats.clarity.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        skadistats.clarity.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CsgoDemoHeader}
     */
    public static final class Builder extends
        skadistats.clarity.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CsgoDemoHeader)
        skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeaderOrBuilder {
      public static final skadistats.clarity.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.internal_static_CsgoDemoHeader_descriptor;
      }

      protected skadistats.clarity.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.internal_static_CsgoDemoHeader_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader.class, skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader.Builder.class);
      }

      // Construct using skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          skadistats.clarity.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (skadistats.clarity.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        demoprotocol_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        networkprotocol_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        servername_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        clientname_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        mapname_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        gamedirectory_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        playbackTime_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000040);
        playbackTicks_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        playbackFrames_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        signonlength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public skadistats.clarity.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.internal_static_CsgoDemoHeader_descriptor;
      }

      public skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader getDefaultInstanceForType() {
        return skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader.getDefaultInstance();
      }

      public skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader build() {
        skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader buildPartial() {
        skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader result = new skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.demoprotocol_ = demoprotocol_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.networkprotocol_ = networkprotocol_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.servername_ = servername_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.clientname_ = clientname_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.mapname_ = mapname_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.gamedirectory_ = gamedirectory_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.playbackTime_ = playbackTime_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.playbackTicks_ = playbackTicks_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.playbackFrames_ = playbackFrames_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.signonlength_ = signonlength_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(skadistats.clarity.protobuf.Message other) {
        if (other instanceof skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader) {
          return mergeFrom((skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader other) {
        if (other == skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader.getDefaultInstance()) return this;
        if (other.hasDemoprotocol()) {
          setDemoprotocol(other.getDemoprotocol());
        }
        if (other.hasNetworkprotocol()) {
          setNetworkprotocol(other.getNetworkprotocol());
        }
        if (other.hasServername()) {
          bitField0_ |= 0x00000004;
          servername_ = other.servername_;
          onChanged();
        }
        if (other.hasClientname()) {
          bitField0_ |= 0x00000008;
          clientname_ = other.clientname_;
          onChanged();
        }
        if (other.hasMapname()) {
          bitField0_ |= 0x00000010;
          mapname_ = other.mapname_;
          onChanged();
        }
        if (other.hasGamedirectory()) {
          bitField0_ |= 0x00000020;
          gamedirectory_ = other.gamedirectory_;
          onChanged();
        }
        if (other.hasPlaybackTime()) {
          setPlaybackTime(other.getPlaybackTime());
        }
        if (other.hasPlaybackTicks()) {
          setPlaybackTicks(other.getPlaybackTicks());
        }
        if (other.hasPlaybackFrames()) {
          setPlaybackFrames(other.getPlaybackFrames());
        }
        if (other.hasSignonlength()) {
          setSignonlength(other.getSignonlength());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          skadistats.clarity.protobuf.CodedInputStream input,
          skadistats.clarity.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (skadistats.clarity.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (skadistats.clarity.wire.cs.csgo.proto.CsgoClarityMessages.CsgoDemoHeader) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int demoprotocol_ ;
      /**
       * <code>optional int32 demoprotocol = 1;</code>
       *
       * <pre>
       * Should be DEMO_PROTOCOL
       * </pre>
       */
      public boolean hasDemoprotocol() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 demoprotocol = 1;</code>
       *
       * <pre>
       * Should be DEMO_PROTOCOL
       * </pre>
       */
      public int getDemoprotocol() {
        return demoprotocol_;
      }
      /**
       * <code>optional int32 demoprotocol = 1;</code>
       *
       * <pre>
       * Should be DEMO_PROTOCOL
       * </pre>
       */
      public Builder setDemoprotocol(int value) {
        bitField0_ |= 0x00000001;
        demoprotocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 demoprotocol = 1;</code>
       *
       * <pre>
       * Should be DEMO_PROTOCOL
       * </pre>
       */
      public Builder clearDemoprotocol() {
        bitField0_ = (bitField0_ & ~0x00000001);
        demoprotocol_ = 0;
        onChanged();
        return this;
      }

      private int networkprotocol_ ;
      /**
       * <code>optional int32 networkprotocol = 2;</code>
       *
       * <pre>
       * Should be PROTOCOL_VERSION
       * </pre>
       */
      public boolean hasNetworkprotocol() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 networkprotocol = 2;</code>
       *
       * <pre>
       * Should be PROTOCOL_VERSION
       * </pre>
       */
      public int getNetworkprotocol() {
        return networkprotocol_;
      }
      /**
       * <code>optional int32 networkprotocol = 2;</code>
       *
       * <pre>
       * Should be PROTOCOL_VERSION
       * </pre>
       */
      public Builder setNetworkprotocol(int value) {
        bitField0_ |= 0x00000002;
        networkprotocol_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 networkprotocol = 2;</code>
       *
       * <pre>
       * Should be PROTOCOL_VERSION
       * </pre>
       */
      public Builder clearNetworkprotocol() {
        bitField0_ = (bitField0_ & ~0x00000002);
        networkprotocol_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object servername_ = "";
      /**
       * <code>optional string servername = 3;</code>
       *
       * <pre>
       * Name of server
       * </pre>
       */
      public boolean hasServername() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string servername = 3;</code>
       *
       * <pre>
       * Name of server
       * </pre>
       */
      public java.lang.String getServername() {
        java.lang.Object ref = servername_;
        if (!(ref instanceof java.lang.String)) {
          skadistats.clarity.protobuf.ByteString bs =
              (skadistats.clarity.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            servername_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string servername = 3;</code>
       *
       * <pre>
       * Name of server
       * </pre>
       */
      public skadistats.clarity.protobuf.ByteString
          getServernameBytes() {
        java.lang.Object ref = servername_;
        if (ref instanceof String) {
          skadistats.clarity.protobuf.ByteString b = 
              skadistats.clarity.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          servername_ = b;
          return b;
        } else {
          return (skadistats.clarity.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string servername = 3;</code>
       *
       * <pre>
       * Name of server
       * </pre>
       */
      public Builder setServername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        servername_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string servername = 3;</code>
       *
       * <pre>
       * Name of server
       * </pre>
       */
      public Builder clearServername() {
        bitField0_ = (bitField0_ & ~0x00000004);
        servername_ = getDefaultInstance().getServername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string servername = 3;</code>
       *
       * <pre>
       * Name of server
       * </pre>
       */
      public Builder setServernameBytes(
          skadistats.clarity.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        servername_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientname_ = "";
      /**
       * <code>optional string clientname = 4;</code>
       *
       * <pre>
       * Name of client who recorded the game
       * </pre>
       */
      public boolean hasClientname() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string clientname = 4;</code>
       *
       * <pre>
       * Name of client who recorded the game
       * </pre>
       */
      public java.lang.String getClientname() {
        java.lang.Object ref = clientname_;
        if (!(ref instanceof java.lang.String)) {
          skadistats.clarity.protobuf.ByteString bs =
              (skadistats.clarity.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string clientname = 4;</code>
       *
       * <pre>
       * Name of client who recorded the game
       * </pre>
       */
      public skadistats.clarity.protobuf.ByteString
          getClientnameBytes() {
        java.lang.Object ref = clientname_;
        if (ref instanceof String) {
          skadistats.clarity.protobuf.ByteString b = 
              skadistats.clarity.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientname_ = b;
          return b;
        } else {
          return (skadistats.clarity.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string clientname = 4;</code>
       *
       * <pre>
       * Name of client who recorded the game
       * </pre>
       */
      public Builder setClientname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        clientname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientname = 4;</code>
       *
       * <pre>
       * Name of client who recorded the game
       * </pre>
       */
      public Builder clearClientname() {
        bitField0_ = (bitField0_ & ~0x00000008);
        clientname_ = getDefaultInstance().getClientname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string clientname = 4;</code>
       *
       * <pre>
       * Name of client who recorded the game
       * </pre>
       */
      public Builder setClientnameBytes(
          skadistats.clarity.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        clientname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mapname_ = "";
      /**
       * <code>optional string mapname = 5;</code>
       *
       * <pre>
       * Name of map
       * </pre>
       */
      public boolean hasMapname() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string mapname = 5;</code>
       *
       * <pre>
       * Name of map
       * </pre>
       */
      public java.lang.String getMapname() {
        java.lang.Object ref = mapname_;
        if (!(ref instanceof java.lang.String)) {
          skadistats.clarity.protobuf.ByteString bs =
              (skadistats.clarity.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mapname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mapname = 5;</code>
       *
       * <pre>
       * Name of map
       * </pre>
       */
      public skadistats.clarity.protobuf.ByteString
          getMapnameBytes() {
        java.lang.Object ref = mapname_;
        if (ref instanceof String) {
          skadistats.clarity.protobuf.ByteString b = 
              skadistats.clarity.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mapname_ = b;
          return b;
        } else {
          return (skadistats.clarity.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mapname = 5;</code>
       *
       * <pre>
       * Name of map
       * </pre>
       */
      public Builder setMapname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mapname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mapname = 5;</code>
       *
       * <pre>
       * Name of map
       * </pre>
       */
      public Builder clearMapname() {
        bitField0_ = (bitField0_ & ~0x00000010);
        mapname_ = getDefaultInstance().getMapname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mapname = 5;</code>
       *
       * <pre>
       * Name of map
       * </pre>
       */
      public Builder setMapnameBytes(
          skadistats.clarity.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        mapname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object gamedirectory_ = "";
      /**
       * <code>optional string gamedirectory = 6;</code>
       *
       * <pre>
       * Name of game directory (com_gamedir)
       * </pre>
       */
      public boolean hasGamedirectory() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string gamedirectory = 6;</code>
       *
       * <pre>
       * Name of game directory (com_gamedir)
       * </pre>
       */
      public java.lang.String getGamedirectory() {
        java.lang.Object ref = gamedirectory_;
        if (!(ref instanceof java.lang.String)) {
          skadistats.clarity.protobuf.ByteString bs =
              (skadistats.clarity.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gamedirectory_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gamedirectory = 6;</code>
       *
       * <pre>
       * Name of game directory (com_gamedir)
       * </pre>
       */
      public skadistats.clarity.protobuf.ByteString
          getGamedirectoryBytes() {
        java.lang.Object ref = gamedirectory_;
        if (ref instanceof String) {
          skadistats.clarity.protobuf.ByteString b = 
              skadistats.clarity.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gamedirectory_ = b;
          return b;
        } else {
          return (skadistats.clarity.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gamedirectory = 6;</code>
       *
       * <pre>
       * Name of game directory (com_gamedir)
       * </pre>
       */
      public Builder setGamedirectory(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        gamedirectory_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gamedirectory = 6;</code>
       *
       * <pre>
       * Name of game directory (com_gamedir)
       * </pre>
       */
      public Builder clearGamedirectory() {
        bitField0_ = (bitField0_ & ~0x00000020);
        gamedirectory_ = getDefaultInstance().getGamedirectory();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gamedirectory = 6;</code>
       *
       * <pre>
       * Name of game directory (com_gamedir)
       * </pre>
       */
      public Builder setGamedirectoryBytes(
          skadistats.clarity.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        gamedirectory_ = value;
        onChanged();
        return this;
      }

      private float playbackTime_ ;
      /**
       * <code>optional float playback_time = 7;</code>
       *
       * <pre>
       * Time of track
       * </pre>
       */
      public boolean hasPlaybackTime() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional float playback_time = 7;</code>
       *
       * <pre>
       * Time of track
       * </pre>
       */
      public float getPlaybackTime() {
        return playbackTime_;
      }
      /**
       * <code>optional float playback_time = 7;</code>
       *
       * <pre>
       * Time of track
       * </pre>
       */
      public Builder setPlaybackTime(float value) {
        bitField0_ |= 0x00000040;
        playbackTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float playback_time = 7;</code>
       *
       * <pre>
       * Time of track
       * </pre>
       */
      public Builder clearPlaybackTime() {
        bitField0_ = (bitField0_ & ~0x00000040);
        playbackTime_ = 0F;
        onChanged();
        return this;
      }

      private int playbackTicks_ ;
      /**
       * <code>optional int32 playback_ticks = 8;</code>
       *
       * <pre>
       * # of ticks in track
       * </pre>
       */
      public boolean hasPlaybackTicks() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 playback_ticks = 8;</code>
       *
       * <pre>
       * # of ticks in track
       * </pre>
       */
      public int getPlaybackTicks() {
        return playbackTicks_;
      }
      /**
       * <code>optional int32 playback_ticks = 8;</code>
       *
       * <pre>
       * # of ticks in track
       * </pre>
       */
      public Builder setPlaybackTicks(int value) {
        bitField0_ |= 0x00000080;
        playbackTicks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playback_ticks = 8;</code>
       *
       * <pre>
       * # of ticks in track
       * </pre>
       */
      public Builder clearPlaybackTicks() {
        bitField0_ = (bitField0_ & ~0x00000080);
        playbackTicks_ = 0;
        onChanged();
        return this;
      }

      private int playbackFrames_ ;
      /**
       * <code>optional int32 playback_frames = 9;</code>
       *
       * <pre>
       * # of frames in track
       * </pre>
       */
      public boolean hasPlaybackFrames() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 playback_frames = 9;</code>
       *
       * <pre>
       * # of frames in track
       * </pre>
       */
      public int getPlaybackFrames() {
        return playbackFrames_;
      }
      /**
       * <code>optional int32 playback_frames = 9;</code>
       *
       * <pre>
       * # of frames in track
       * </pre>
       */
      public Builder setPlaybackFrames(int value) {
        bitField0_ |= 0x00000100;
        playbackFrames_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 playback_frames = 9;</code>
       *
       * <pre>
       * # of frames in track
       * </pre>
       */
      public Builder clearPlaybackFrames() {
        bitField0_ = (bitField0_ & ~0x00000100);
        playbackFrames_ = 0;
        onChanged();
        return this;
      }

      private int signonlength_ ;
      /**
       * <code>optional int32 signonlength = 10;</code>
       *
       * <pre>
       * length of sigondata in bytes
       * </pre>
       */
      public boolean hasSignonlength() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional int32 signonlength = 10;</code>
       *
       * <pre>
       * length of sigondata in bytes
       * </pre>
       */
      public int getSignonlength() {
        return signonlength_;
      }
      /**
       * <code>optional int32 signonlength = 10;</code>
       *
       * <pre>
       * length of sigondata in bytes
       * </pre>
       */
      public Builder setSignonlength(int value) {
        bitField0_ |= 0x00000200;
        signonlength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 signonlength = 10;</code>
       *
       * <pre>
       * length of sigondata in bytes
       * </pre>
       */
      public Builder clearSignonlength() {
        bitField0_ = (bitField0_ & ~0x00000200);
        signonlength_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CsgoDemoHeader)
    }

    static {
      defaultInstance = new CsgoDemoHeader(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CsgoDemoHeader)
  }

  private static final skadistats.clarity.protobuf.Descriptors.Descriptor
    internal_static_CsgoDemoHeader_descriptor;
  private static
    skadistats.clarity.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CsgoDemoHeader_fieldAccessorTable;

  public static skadistats.clarity.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static skadistats.clarity.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025claritymessages.proto\"\355\001\n\016CsgoDemoHead" +
      "er\022\024\n\014demoprotocol\030\001 \001(\005\022\027\n\017networkproto" +
      "col\030\002 \001(\005\022\022\n\nservername\030\003 \001(\t\022\022\n\nclientn" +
      "ame\030\004 \001(\t\022\017\n\007mapname\030\005 \001(\t\022\025\n\rgamedirect" +
      "ory\030\006 \001(\t\022\025\n\rplayback_time\030\007 \001(\002\022\026\n\016play" +
      "back_ticks\030\010 \001(\005\022\027\n\017playback_frames\030\t \001(" +
      "\005\022\024\n\014signonlength\030\n \001(\005B<\n%skadistats.cl" +
      "arity.wire.cs.csgo.protoB\023CsgoClarityMes" +
      "sages"
    };
    skadistats.clarity.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new skadistats.clarity.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public skadistats.clarity.protobuf.ExtensionRegistry assignDescriptors(
              skadistats.clarity.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    skadistats.clarity.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new skadistats.clarity.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CsgoDemoHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CsgoDemoHeader_fieldAccessorTable = new
      skadistats.clarity.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CsgoDemoHeader_descriptor,
        new java.lang.String[] { "Demoprotocol", "Networkprotocol", "Servername", "Clientname", "Mapname", "Gamedirectory", "PlaybackTime", "PlaybackTicks", "PlaybackFrames", "Signonlength", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
