// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gcsdk_gcmessages.proto

package skadistats.clarity.wire.shared.common.proto;

public final class GcSdkGcMessages {
  private GcSdkGcMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CExtraMsgBlockOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CExtraMsgBlock)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 msg_type = 1;</code>
     */
    boolean hasMsgType();
    /**
     * <code>optional uint32 msg_type = 1;</code>
     */
    int getMsgType();

    /**
     * <code>optional bytes contents = 2;</code>
     */
    boolean hasContents();
    /**
     * <code>optional bytes contents = 2;</code>
     */
    com.google.protobuf.ByteString getContents();

    /**
     * <code>optional uint64 msg_key = 3;</code>
     */
    boolean hasMsgKey();
    /**
     * <code>optional uint64 msg_key = 3;</code>
     */
    long getMsgKey();

    /**
     * <code>optional bool is_compressed = 4;</code>
     */
    boolean hasIsCompressed();
    /**
     * <code>optional bool is_compressed = 4;</code>
     */
    boolean getIsCompressed();
  }
  /**
   * Protobuf type {@code CExtraMsgBlock}
   */
  public static final class CExtraMsgBlock extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:CExtraMsgBlock)
      CExtraMsgBlockOrBuilder {
    // Use CExtraMsgBlock.newBuilder() to construct.
    private CExtraMsgBlock(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private CExtraMsgBlock(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final CExtraMsgBlock defaultInstance;
    public static CExtraMsgBlock getDefaultInstance() {
      return defaultInstance;
    }

    public CExtraMsgBlock getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private CExtraMsgBlock(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              msgType_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              contents_ = input.readBytes();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              msgKey_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              isCompressed_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.internal_static_CExtraMsgBlock_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.internal_static_CExtraMsgBlock_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock.class, skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock.Builder.class);
    }

    public static com.google.protobuf.Parser<CExtraMsgBlock> PARSER =
        new com.google.protobuf.AbstractParser<CExtraMsgBlock>() {
      public CExtraMsgBlock parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CExtraMsgBlock(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<CExtraMsgBlock> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MSG_TYPE_FIELD_NUMBER = 1;
    private int msgType_;
    /**
     * <code>optional uint32 msg_type = 1;</code>
     */
    public boolean hasMsgType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint32 msg_type = 1;</code>
     */
    public int getMsgType() {
      return msgType_;
    }

    public static final int CONTENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString contents_;
    /**
     * <code>optional bytes contents = 2;</code>
     */
    public boolean hasContents() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes contents = 2;</code>
     */
    public com.google.protobuf.ByteString getContents() {
      return contents_;
    }

    public static final int MSG_KEY_FIELD_NUMBER = 3;
    private long msgKey_;
    /**
     * <code>optional uint64 msg_key = 3;</code>
     */
    public boolean hasMsgKey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 msg_key = 3;</code>
     */
    public long getMsgKey() {
      return msgKey_;
    }

    public static final int IS_COMPRESSED_FIELD_NUMBER = 4;
    private boolean isCompressed_;
    /**
     * <code>optional bool is_compressed = 4;</code>
     */
    public boolean hasIsCompressed() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional bool is_compressed = 4;</code>
     */
    public boolean getIsCompressed() {
      return isCompressed_;
    }

    private void initFields() {
      msgType_ = 0;
      contents_ = com.google.protobuf.ByteString.EMPTY;
      msgKey_ = 0L;
      isCompressed_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, contents_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, msgKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBool(4, isCompressed_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, msgType_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, contents_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, msgKey_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isCompressed_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code CExtraMsgBlock}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CExtraMsgBlock)
        skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlockOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.internal_static_CExtraMsgBlock_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.internal_static_CExtraMsgBlock_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock.class, skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock.Builder.class);
      }

      // Construct using skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        contents_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        msgKey_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        isCompressed_ = false;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.internal_static_CExtraMsgBlock_descriptor;
      }

      public skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock getDefaultInstanceForType() {
        return skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock.getDefaultInstance();
      }

      public skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock build() {
        skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock buildPartial() {
        skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock result = new skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgType_ = msgType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.contents_ = contents_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.msgKey_ = msgKey_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.isCompressed_ = isCompressed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock) {
          return mergeFrom((skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock other) {
        if (other == skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock.getDefaultInstance()) return this;
        if (other.hasMsgType()) {
          setMsgType(other.getMsgType());
        }
        if (other.hasContents()) {
          setContents(other.getContents());
        }
        if (other.hasMsgKey()) {
          setMsgKey(other.getMsgKey());
        }
        if (other.hasIsCompressed()) {
          setIsCompressed(other.getIsCompressed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (skadistats.clarity.wire.shared.common.proto.GcSdkGcMessages.CExtraMsgBlock) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int msgType_ ;
      /**
       * <code>optional uint32 msg_type = 1;</code>
       */
      public boolean hasMsgType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint32 msg_type = 1;</code>
       */
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>optional uint32 msg_type = 1;</code>
       */
      public Builder setMsgType(int value) {
        bitField0_ |= 0x00000001;
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 msg_type = 1;</code>
       */
      public Builder clearMsgType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString contents_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes contents = 2;</code>
       */
      public boolean hasContents() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes contents = 2;</code>
       */
      public com.google.protobuf.ByteString getContents() {
        return contents_;
      }
      /**
       * <code>optional bytes contents = 2;</code>
       */
      public Builder setContents(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        contents_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes contents = 2;</code>
       */
      public Builder clearContents() {
        bitField0_ = (bitField0_ & ~0x00000002);
        contents_ = getDefaultInstance().getContents();
        onChanged();
        return this;
      }

      private long msgKey_ ;
      /**
       * <code>optional uint64 msg_key = 3;</code>
       */
      public boolean hasMsgKey() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 msg_key = 3;</code>
       */
      public long getMsgKey() {
        return msgKey_;
      }
      /**
       * <code>optional uint64 msg_key = 3;</code>
       */
      public Builder setMsgKey(long value) {
        bitField0_ |= 0x00000004;
        msgKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 msg_key = 3;</code>
       */
      public Builder clearMsgKey() {
        bitField0_ = (bitField0_ & ~0x00000004);
        msgKey_ = 0L;
        onChanged();
        return this;
      }

      private boolean isCompressed_ ;
      /**
       * <code>optional bool is_compressed = 4;</code>
       */
      public boolean hasIsCompressed() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional bool is_compressed = 4;</code>
       */
      public boolean getIsCompressed() {
        return isCompressed_;
      }
      /**
       * <code>optional bool is_compressed = 4;</code>
       */
      public Builder setIsCompressed(boolean value) {
        bitField0_ |= 0x00000008;
        isCompressed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_compressed = 4;</code>
       */
      public Builder clearIsCompressed() {
        bitField0_ = (bitField0_ & ~0x00000008);
        isCompressed_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:CExtraMsgBlock)
    }

    static {
      defaultInstance = new CExtraMsgBlock(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:CExtraMsgBlock)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CExtraMsgBlock_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CExtraMsgBlock_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026gcsdk_gcmessages.proto\"\\\n\016CExtraMsgBlo" +
      "ck\022\020\n\010msg_type\030\001 \001(\r\022\020\n\010contents\030\002 \001(\014\022\017" +
      "\n\007msg_key\030\003 \001(\004\022\025\n\ris_compressed\030\004 \001(\010B>" +
      "\n+skadistats.clarity.wire.shared.common." +
      "protoB\017GcSdkGcMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CExtraMsgBlock_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CExtraMsgBlock_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_CExtraMsgBlock_descriptor,
        new java.lang.String[] { "MsgType", "Contents", "MsgKey", "IsCompressed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
