package skadistats.clarity.wire.s2;

import com.google.protobuf.GeneratedMessage;
import skadistats.clarity.wire.common.proto.NetmessagesCommon;
import skadistats.clarity.wire.common.proto.Networkbasetypes;
import skadistats.clarity.wire.s2.proto.*;

import java.util.HashMap;
import java.util.Map;

public class EmbeddedPackets {

    private static final Map<Integer, Class<? extends GeneratedMessage>> EMBED;
    static {
        EMBED = new HashMap<>();
        /*   4 */ EMBED.put(Networkbasetypes.NET_Messages.net_Tick_VALUE, Networkbasetypes.CNETMsg_Tick.class);
        /*   6 */ EMBED.put(Networkbasetypes.NET_Messages.net_SetConVar_VALUE, Networkbasetypes.CNETMsg_SetConVar.class);
        /*   7 */ EMBED.put(Networkbasetypes.NET_Messages.net_SignonState_VALUE, Networkbasetypes.CNETMsg_SignonState.class);
        /*   8 */ EMBED.put(Networkbasetypes.NET_Messages.net_SpawnGroup_Load_VALUE, Networkbasetypes.CNETMsg_SpawnGroup_Load.class);
        /*   9 */ EMBED.put(Networkbasetypes.NET_Messages.net_SpawnGroup_ManifestUpdate_VALUE, Networkbasetypes.CNETMsg_SpawnGroup_ManifestUpdate.class);
        /*  11 */ EMBED.put(Networkbasetypes.NET_Messages.net_SpawnGroup_SetCreationTick_VALUE, Networkbasetypes.CNETMsg_SpawnGroup_SetCreationTick.class);
        /*  12 */ EMBED.put(Networkbasetypes.NET_Messages.net_SpawnGroup_Unload_VALUE, Networkbasetypes.CNETMsg_SpawnGroup_Unload.class);

        /*  40 */ EMBED.put(Netmessages.SVC_Messages.svc_ServerInfo_VALUE, Netmessages.CSVCMsg_ServerInfo.class);
        /*  41 */ EMBED.put(Netmessages.SVC_Messages.svc_FlattenedSerializer_VALUE, Netmessages.CSVCMsg_FlattenedSerializer.class);
        /*  42 */ EMBED.put(Netmessages.SVC_Messages.svc_ClassInfo_VALUE, Netmessages.CSVCMsg_ClassInfo.class);
        /*  44 */ EMBED.put(Netmessages.SVC_Messages.svc_CreateStringTable_VALUE, Netmessages.CSVCMsg_CreateStringTable.class);
        /*  45 */ EMBED.put(Netmessages.SVC_Messages.svc_UpdateStringTable_VALUE, Netmessages.CSVCMsg_UpdateStringTable.class);
        /*  46 */ EMBED.put(Netmessages.SVC_Messages.svc_VoiceInit_VALUE, Netmessages.CSVCMsg_VoiceInit.class);
        /*  50 */ EMBED.put(Netmessages.SVC_Messages.svc_SetView_VALUE, Netmessages.CSVCMsg_SetView.class);
        /*  51 */ EMBED.put(Netmessages.SVC_Messages.svc_ClearAllStringTables_VALUE, Netmessages.CSVCMsg_ClearAllStringTables.class);
        /*  55 */ EMBED.put(Netmessages.SVC_Messages.svc_PacketEntities_VALUE, NetmessagesCommon.CSVCMsg_PacketEntities.class);

        /* 101 */ EMBED.put(Usermessages.EBaseUserMessages.UM_AchievementEvent_VALUE, Usermessages.CUserMessageAchievementEvent.class);
        /* 102 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CloseCaption_VALUE, Usermessages.CUserMessageCloseCaption.class);
        /* 103 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CloseCaptionDirect_VALUE, Usermessages.CUserMessageCloseCaptionDirect.class);
        /* 104 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CurrentTimescale_VALUE, Usermessages.CUserMessageCurrentTimescale.class);
        /* 105 */ EMBED.put(Usermessages.EBaseUserMessages.UM_DesiredTimescale_VALUE, Usermessages.CUserMessageDesiredTimescale.class);
        /* 106 */ EMBED.put(Usermessages.EBaseUserMessages.UM_Fade_VALUE, Usermessages.CUserMessageFade.class);
        /* 107 */ EMBED.put(Usermessages.EBaseUserMessages.UM_GameTitle_VALUE, Usermessages.CUserMessageGameTitle.class);
        /* 109 */ EMBED.put(Usermessages.EBaseUserMessages.UM_HintText_VALUE, Usermessages.CUserMessageHintText.class);
        /* 110 */ EMBED.put(Usermessages.EBaseUserMessages.UM_HudMsg_VALUE, Usermessages.CUserMessageHudMsg.class);
        /* 111 */ EMBED.put(Usermessages.EBaseUserMessages.UM_HudText_VALUE, Usermessages.CUserMessageHudText.class);
        /* 112 */ EMBED.put(Usermessages.EBaseUserMessages.UM_KeyHintText_VALUE, Usermessages.CUserMessageKeyHintText.class);
        /* 113 */ EMBED.put(Usermessages.EBaseUserMessages.UM_ColoredText_VALUE, Usermessages.CUserMessageColoredText.class);
        /* 114 */ EMBED.put(Usermessages.EBaseUserMessages.UM_RequestState_VALUE, Usermessages.CUserMessageRequestState.class);
        /* 115 */ EMBED.put(Usermessages.EBaseUserMessages.UM_ResetHUD_VALUE, Usermessages.CUserMessageResetHUD.class);
        /* 116 */ EMBED.put(Usermessages.EBaseUserMessages.UM_Rumble_VALUE, Usermessages.CUserMessageRumble.class);
        /* 117 */ EMBED.put(Usermessages.EBaseUserMessages.UM_SayText_VALUE, Usermessages.CUserMessageSayText.class);
        /* 118 */ EMBED.put(Usermessages.EBaseUserMessages.UM_SayText2_VALUE, Usermessages.CUserMessageSayText2.class);
        /* 119 */ EMBED.put(Usermessages.EBaseUserMessages.UM_SayTextChannel_VALUE, Usermessages.CUserMessageSayTextChannel.class);
        /* 120 */ EMBED.put(Usermessages.EBaseUserMessages.UM_Shake_VALUE, Usermessages.CUserMessageShake.class);
        /* 121 */ EMBED.put(Usermessages.EBaseUserMessages.UM_ShakeDir_VALUE, Usermessages.CUserMessageShakeDir.class);
        /* 124 */ EMBED.put(Usermessages.EBaseUserMessages.UM_TextMsg_VALUE, Usermessages.CUserMessageTextMsg.class);
        /* 125 */ EMBED.put(Usermessages.EBaseUserMessages.UM_ScreenTilt_VALUE, Usermessages.CUserMessageScreenTilt.class);
        /* 126 */ EMBED.put(Usermessages.EBaseUserMessages.UM_Train_VALUE, Usermessages.CUserMessageTrain.class);
        /* 127 */ EMBED.put(Usermessages.EBaseUserMessages.UM_VGUIMenu_VALUE, Usermessages.CUserMessageVGUIMenu.class);
        /* 128 */ EMBED.put(Usermessages.EBaseUserMessages.UM_VoiceMask_VALUE, Usermessages.CUserMessageVoiceMask.class);
        /* 129 */ EMBED.put(Usermessages.EBaseUserMessages.UM_VoiceSubtitle_VALUE, Usermessages.CUserMessageVoiceSubtitle.class);
        /* 130 */ EMBED.put(Usermessages.EBaseUserMessages.UM_SendAudio_VALUE, Usermessages.CUserMessageSendAudio.class);
        /* 131 */ EMBED.put(Usermessages.EBaseUserMessages.UM_ItemPickup_VALUE, Usermessages.CUserMessageItemPickup.class);
        /* 132 */ EMBED.put(Usermessages.EBaseUserMessages.UM_AmmoDenied_VALUE, Usermessages.CUserMessageAmmoDenied.class);
        /* 133 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CrosshairAngle_VALUE, Usermessages.CUserMessageCrosshairAngle.class);
        /* 134 */ EMBED.put(Usermessages.EBaseUserMessages.UM_ShowMenu_VALUE, Usermessages.CUserMessageShowMenu.class);
        /* 135 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CreditsMsg_VALUE, Usermessages.CUserMessageCreditsMsg.class);
        /* 142 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CloseCaptionPlaceholder_VALUE, Usermessages.CUserMessageCloseCaptionPlaceholder.class);
        /* 143 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CameraTransition_VALUE, Usermessages.CUserMessageCameraTransition.class);
        /* 144 */ EMBED.put(Usermessages.EBaseUserMessages.UM_AudioParameter_VALUE, Usermessages.CUserMessageAudioParameter.class);
        /* 145 */ EMBED.put(Usermessages.EBaseUserMessages.UM_ParticleManager_VALUE, null);
        /* 146 */ EMBED.put(Usermessages.EBaseUserMessages.UM_HudError_VALUE, null);
        /* 147 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CustomGameEvent_ClientToServer_VALUE, null);
        /* 148 */ EMBED.put(Usermessages.EBaseUserMessages.UM_CustomGameEvent_ServerToClient_VALUE, null);
        /* 149 */ EMBED.put(Usermessages.EBaseUserMessages.UM_TrackedControllerInput_ClientToServer_VALUE, null);

        /* 200 */ EMBED.put(Gameevents.EBaseGameEvents.GE_VDebugGameSessionIDEvent_VALUE, Gameevents.CMsgVDebugGameSessionIDEvent.class);
        /* 201 */ EMBED.put(Gameevents.EBaseGameEvents.GE_PlaceDecalEvent_VALUE, Gameevents.CMsgPlaceDecalEvent.class);
        /* 202 */ EMBED.put(Gameevents.EBaseGameEvents.GE_ClearWorldDecalsEvent_VALUE, Gameevents.CMsgClearWorldDecalsEvent.class);
        /* 203 */ EMBED.put(Gameevents.EBaseGameEvents.GE_ClearEntityDecalsEvent_VALUE, Gameevents.CMsgClearEntityDecalsEvent.class);
        /* 204 */ EMBED.put(Gameevents.EBaseGameEvents.GE_ClearDecalsForSkeletonInstanceEvent_VALUE, Gameevents.CMsgClearDecalsForSkeletonInstanceEvent.class);
        /* 205 */ EMBED.put(Gameevents.EBaseGameEvents.GE_Source1LegacyGameEventList_VALUE, NetmessagesCommon.CSVCMsg_GameEventList.class);
        /* 206 */ EMBED.put(Gameevents.EBaseGameEvents.GE_Source1LegacyListenEvents_VALUE, Gameevents.CMsgSource1LegacyListenEvents.class);
        /* 207 */ EMBED.put(Gameevents.EBaseGameEvents.GE_Source1LegacyGameEvent_VALUE, Networkbasetypes.CSVCMsg_GameEvent.class);
        /* 208 */ EMBED.put(Gameevents.EBaseGameEvents.GE_SosStartSoundEvent_VALUE, Gameevents.CMsgSosStartSoundEvent.class);
        /* 209 */ EMBED.put(Gameevents.EBaseGameEvents.GE_SosStopSoundEvent_VALUE, Gameevents.CMsgSosStopSoundEvent.class);
        /* 210 */ EMBED.put(Gameevents.EBaseGameEvents.GE_SosSetSoundEventParams_VALUE, Gameevents.CMsgSosSetSoundEventParams.class);
        /* 211 */ EMBED.put(Gameevents.EBaseGameEvents.GE_SosSetLibraryStackFields_VALUE, Gameevents.CMsgSosSetLibraryStackFields.class);
        /* 212 */ EMBED.put(Gameevents.EBaseGameEvents.GE_SosStopSoundEventHash_VALUE, Gameevents.CMsgSosStopSoundEventHash.class);

        /* 400 */ EMBED.put(Te.ETEProtobufIds.TE_EffectDispatchId_VALUE, Te.CMsgTEEffectDispatch.class);

        /* 464 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_AddUnitToSelection_VALUE, null);
        /* 465 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_AIDebugLine_VALUE, DotaUsermessages.CDOTAUserMsg_AIDebugLine.class);
        /* 466 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ChatEvent_VALUE, DotaUsermessages.CDOTAUserMsg_ChatEvent.class);
        /* 467 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CombatHeroPositions_VALUE, DotaUsermessages.CDOTAUserMsg_CombatHeroPositions.class);
        /* 468 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CombatLogData_VALUE, null);
        /* 470 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CombatLogShowDeath_VALUE, DotaUsermessages.CDOTAUserMsg_CombatLogShowDeath.class);
        /* 471 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CreateLinearProjectile_VALUE, DotaUsermessages.CDOTAUserMsg_CreateLinearProjectile.class);
        /* 472 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_DestroyLinearProjectile_VALUE, DotaUsermessages.CDOTAUserMsg_DestroyLinearProjectile.class);
        /* 473 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_DodgeTrackingProjectiles_VALUE, DotaUsermessages.CDOTAUserMsg_DodgeTrackingProjectiles.class);
        /* 474 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_GlobalLightColor_VALUE, DotaUsermessages.CDOTAUserMsg_GlobalLightColor.class);
        /* 475 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_GlobalLightDirection_VALUE, DotaUsermessages.CDOTAUserMsg_GlobalLightDirection.class);
        /* 476 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_InvalidCommand_VALUE, DotaUsermessages.CDOTAUserMsg_InvalidCommand.class);
        /* 477 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_LocationPing_VALUE, DotaUsermessages.CDOTAUserMsg_LocationPing.class);
        /* 478 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_MapLine_VALUE, DotaUsermessages.CDOTAUserMsg_MapLine.class);
        /* 479 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_MiniKillCamInfo_VALUE, DotaUsermessages.CDOTAUserMsg_MiniKillCamInfo.class);
        /* 480 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_MinimapDebugPoint_VALUE, DotaUsermessages.CDOTAUserMsg_MinimapDebugPoint.class);
        /* 481 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_MinimapEvent_VALUE, DotaUsermessages.CDOTAUserMsg_MinimapEvent.class);
        /* 482 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_NevermoreRequiem_VALUE, DotaUsermessages.CDOTAUserMsg_NevermoreRequiem.class);
        /* 483 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_OverheadEvent_VALUE, DotaUsermessages.CDOTAUserMsg_OverheadEvent.class);
        /* 484 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SetNextAutobuyItem_VALUE, DotaUsermessages.CDOTAUserMsg_SetNextAutobuyItem.class);
        /* 485 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SharedCooldown_VALUE, DotaUsermessages.CDOTAUserMsg_SharedCooldown.class);
        /* 486 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SpectatorPlayerClick_VALUE, DotaUsermessages.CDOTAUserMsg_SpectatorPlayerClick.class);
        /* 487 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TutorialTipInfo_VALUE, DotaUsermessages.CDOTAUserMsg_TutorialTipInfo.class);
        /* 488 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_UnitEvent_VALUE, DotaUsermessages.CDOTAUserMsg_UnitEvent.class);
        /* 489 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ParticleManager_VALUE, DotaUsermessages.CDOTAUserMsg_ParticleManager.class);
        /* 490 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_BotChat_VALUE, DotaUsermessages.CDOTAUserMsg_BotChat.class);
        /* 491 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_HudError_VALUE, DotaUsermessages.CDOTAUserMsg_HudError.class);
        /* 492 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ItemPurchased_VALUE, DotaUsermessages.CDOTAUserMsg_ItemPurchased.class);
        /* 493 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_Ping_VALUE, DotaUsermessages.CDOTAUserMsg_Ping.class);
        /* 494 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ItemFound_VALUE, DotaUsermessages.CDOTAUserMsg_ItemFound.class);
        /* 495 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CharacterSpeakConcept_VALUE, null);
        /* 496 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SwapVerify_VALUE, DotaUsermessages.CDOTAUserMsg_SwapVerify.class);
        /* 497 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_WorldLine_VALUE, DotaUsermessages.CDOTAUserMsg_WorldLine.class);
        /* 498 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TournamentDrop_VALUE, null);
        /* 499 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ItemAlert_VALUE, DotaUsermessages.CDOTAUserMsg_ItemAlert.class);
        /* 500 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_HalloweenDrops_VALUE, DotaUsermessages.CDOTAUserMsg_HalloweenDrops.class);
        /* 501 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ChatWheel_VALUE, DotaUsermessages.CDOTAUserMsg_ChatWheel.class);
        /* 502 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ReceivedXmasGift_VALUE, DotaUsermessages.CDOTAUserMsg_ReceivedXmasGift.class);
        /* 503 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_UpdateSharedContent_VALUE, DotaUsermessages.CDOTAUserMsg_UpdateSharedContent.class);
        /* 504 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TutorialRequestExp_VALUE, DotaUsermessages.CDOTAUserMsg_TutorialRequestExp.class);
        /* 505 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TutorialPingMinimap_VALUE, DotaUsermessages.CDOTAUserMsg_TutorialPingMinimap.class);
        /* 506 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_GamerulesStateChanged_VALUE, DotaUsermessages.CDOTAUserMsg_GamerulesStateChanged.class);
        /* 507 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ShowSurvey_VALUE, DotaUsermessages.CDOTAUserMsg_ShowSurvey.class);
        /* 508 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TutorialFade_VALUE, DotaUsermessages.CDOTAUserMsg_TutorialFade.class);
        /* 509 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_AddQuestLogEntry_VALUE, DotaUsermessages.CDOTAUserMsg_AddQuestLogEntry.class);
        /* 510 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SendStatPopup_VALUE, DotaUsermessages.CDOTAUserMsg_SendStatPopup.class);
        /* 511 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TutorialFinish_VALUE, DotaUsermessages.CDOTAUserMsg_TutorialFinish.class);
        /* 512 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SendRoshanPopup_VALUE, DotaUsermessages.CDOTAUserMsg_SendRoshanPopup.class);
        /* 513 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SendGenericToolTip_VALUE, DotaUsermessages.CDOTAUserMsg_SendGenericToolTip.class);
        /* 514 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SendFinalGold_VALUE, DotaUsermessages.CDOTAUserMsg_SendFinalGold.class);
        /* 515 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CustomMsg_VALUE, DotaUsermessages.CDOTAUserMsg_CustomMsg.class);
        /* 516 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CoachHUDPing_VALUE, DotaUsermessages.CDOTAUserMsg_CoachHUDPing.class);
        /* 517 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ClientLoadGridNav_VALUE, DotaUsermessages.CDOTAUserMsg_ClientLoadGridNav.class);
        /* 518 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TE_Projectile_VALUE, DotaUsermessages.CDOTAUserMsg_TE_Projectile.class);
        /* 519 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TE_ProjectileLoc_VALUE, DotaUsermessages.CDOTAUserMsg_TE_ProjectileLoc.class);
        /* 520 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TE_DotaBloodImpact_VALUE, DotaUsermessages.CDOTAUserMsg_TE_DotaBloodImpact.class);
        /* 521 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TE_UnitAnimation_VALUE, DotaUsermessages.CDOTAUserMsg_TE_UnitAnimation.class);
        /* 522 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TE_UnitAnimationEnd_VALUE, DotaUsermessages.CDOTAUserMsg_TE_UnitAnimationEnd.class);
        /* 523 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_AbilityPing_VALUE, DotaUsermessages.CDOTAUserMsg_AbilityPing.class);
        /* 524 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ShowGenericPopup_VALUE, DotaUsermessages.CDOTAUserMsg_ShowGenericPopup.class);
        /* 525 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_VoteStart_VALUE, DotaUsermessages.CDOTAUserMsg_VoteStart.class);
        /* 526 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_VoteUpdate_VALUE, DotaUsermessages.CDOTAUserMsg_VoteUpdate.class);
        /* 527 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_VoteEnd_VALUE, DotaUsermessages.CDOTAUserMsg_VoteEnd.class);
        /* 528 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_BoosterState_VALUE, DotaUsermessages.CDOTAUserMsg_BoosterState.class);
        /* 529 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_WillPurchaseAlert_VALUE, DotaUsermessages.CDOTAUserMsg_WillPurchaseAlert.class);
        /* 530 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_TutorialMinimapPosition_VALUE, DotaUsermessages.CDOTAUserMsg_TutorialMinimapPosition.class);
        /* 531 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_PlayerMMR_VALUE, DotaUsermessages.CDOTAUserMsg_PlayerMMR.class);
        /* 532 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_AbilitySteal_VALUE, DotaUsermessages.CDOTAUserMsg_AbilitySteal.class);
        /* 533 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CourierKilledAlert_VALUE, DotaUsermessages.CDOTAUserMsg_CourierKilledAlert.class);
        /* 534 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_EnemyItemAlert_VALUE, DotaUsermessages.CDOTAUserMsg_EnemyItemAlert.class);
        /* 535 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_StatsMatchDetails_VALUE, DotaUsermessages.CDOTAUserMsg_StatsMatchDetails.class);
        /* 536 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_MiniTaunt_VALUE, DotaUsermessages.CDOTAUserMsg_MiniTaunt.class);
        /* 537 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_BuyBackStateAlert_VALUE, DotaUsermessages.CDOTAUserMsg_BuyBackStateAlert.class);
        /* 538 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SpeechBubble_VALUE, DotaUsermessages.CDOTAUserMsg_SpeechBubble.class);
        /* 539 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CustomHeaderMessage_VALUE, DotaUsermessages.CDOTAUserMsg_CustomHeaderMessage.class);
        /* 540 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_QuickBuyAlert_VALUE, DotaUsermessages.CDOTAUserMsg_QuickBuyAlert.class);
        /* 541 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_StatsHeroDetails_VALUE, DotaUsermessages.CDOTAUserMsg_StatsHeroMinuteDetails.class);
        /* 542 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_PredictionResult_VALUE, DotaUsermessages.CDOTAUserMsg_PredictionResult.class);
        /* 543 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_ModifierAlert_VALUE, DotaUsermessages.CDOTAUserMsg_ModifierAlert.class);
        /* 544 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_HPManaAlert_VALUE, DotaUsermessages.CDOTAUserMsg_HPManaAlert.class);
        /* 545 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_GlyphAlert_VALUE, DotaUsermessages.CDOTAUserMsg_GlyphAlert.class);
        /* 546 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_BeastChat_VALUE, DotaUsermessages.CDOTAUserMsg_BeastChat.class);
        /* 547 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_SpectatorPlayerUnitOrders_VALUE, DotaUsermessages.CDOTAUserMsg_SpectatorPlayerUnitOrders.class);
        /* 548 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CustomHudElement_Create_VALUE, DotaUsermessages.CDOTAUserMsg_CustomHudElement_Create.class);
        /* 549 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CustomHudElement_Modify_VALUE, DotaUsermessages.CDOTAUserMsg_CustomHudElement_Modify.class);
        /* 550 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CustomHudElement_Destroy_VALUE, DotaUsermessages.CDOTAUserMsg_CustomHudElement_Destroy.class);
        /* 551 */ EMBED.put(DotaUsermessages.EDotaUserMessages.DOTA_UM_CompendiumState_VALUE, DotaUsermessages.CDOTAUserMsg_CompendiumState.class);
    }

    public static Class<? extends GeneratedMessage> classForKind(int kind) {
        return EMBED.get(kind);
    }

}
