// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dota_usermessages_common.proto

package skadistats.clarity.wire.common.proto;

public final class DotaUserMessages {
  private DotaUserMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code DOTA_COMBATLOG_TYPES}
   */
  public enum DOTA_COMBATLOG_TYPES
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DOTA_COMBATLOG_DAMAGE = 0;</code>
     */
    DOTA_COMBATLOG_DAMAGE(0, 0),
    /**
     * <code>DOTA_COMBATLOG_HEAL = 1;</code>
     */
    DOTA_COMBATLOG_HEAL(1, 1),
    /**
     * <code>DOTA_COMBATLOG_MODIFIER_ADD = 2;</code>
     */
    DOTA_COMBATLOG_MODIFIER_ADD(2, 2),
    /**
     * <code>DOTA_COMBATLOG_MODIFIER_REMOVE = 3;</code>
     */
    DOTA_COMBATLOG_MODIFIER_REMOVE(3, 3),
    /**
     * <code>DOTA_COMBATLOG_DEATH = 4;</code>
     */
    DOTA_COMBATLOG_DEATH(4, 4),
    /**
     * <code>DOTA_COMBATLOG_ABILITY = 5;</code>
     */
    DOTA_COMBATLOG_ABILITY(5, 5),
    /**
     * <code>DOTA_COMBATLOG_ITEM = 6;</code>
     */
    DOTA_COMBATLOG_ITEM(6, 6),
    /**
     * <code>DOTA_COMBATLOG_LOCATION = 7;</code>
     */
    DOTA_COMBATLOG_LOCATION(7, 7),
    /**
     * <code>DOTA_COMBATLOG_GOLD = 8;</code>
     */
    DOTA_COMBATLOG_GOLD(8, 8),
    /**
     * <code>DOTA_COMBATLOG_GAME_STATE = 9;</code>
     */
    DOTA_COMBATLOG_GAME_STATE(9, 9),
    /**
     * <code>DOTA_COMBATLOG_XP = 10;</code>
     */
    DOTA_COMBATLOG_XP(10, 10),
    /**
     * <code>DOTA_COMBATLOG_PURCHASE = 11;</code>
     */
    DOTA_COMBATLOG_PURCHASE(11, 11),
    /**
     * <code>DOTA_COMBATLOG_BUYBACK = 12;</code>
     */
    DOTA_COMBATLOG_BUYBACK(12, 12),
    /**
     * <code>DOTA_COMBATLOG_ABILITY_TRIGGER = 13;</code>
     */
    DOTA_COMBATLOG_ABILITY_TRIGGER(13, 13),
    /**
     * <code>DOTA_COMBATLOG_PLAYERSTATS = 14;</code>
     */
    DOTA_COMBATLOG_PLAYERSTATS(14, 14),
    /**
     * <code>DOTA_COMBATLOG_MULTIKILL = 15;</code>
     */
    DOTA_COMBATLOG_MULTIKILL(15, 15),
    /**
     * <code>DOTA_COMBATLOG_KILLSTREAK = 16;</code>
     */
    DOTA_COMBATLOG_KILLSTREAK(16, 16),
    /**
     * <code>DOTA_COMBATLOG_TEAM_BUILDING_KILL = 17;</code>
     */
    DOTA_COMBATLOG_TEAM_BUILDING_KILL(17, 17),
    /**
     * <code>DOTA_COMBATLOG_FIRST_BLOOD = 18;</code>
     */
    DOTA_COMBATLOG_FIRST_BLOOD(18, 18),
    /**
     * <code>DOTA_COMBATLOG_MODIFIER_REFRESH = 19;</code>
     */
    DOTA_COMBATLOG_MODIFIER_REFRESH(19, 19),
    ;

    /**
     * <code>DOTA_COMBATLOG_DAMAGE = 0;</code>
     */
    public static final int DOTA_COMBATLOG_DAMAGE_VALUE = 0;
    /**
     * <code>DOTA_COMBATLOG_HEAL = 1;</code>
     */
    public static final int DOTA_COMBATLOG_HEAL_VALUE = 1;
    /**
     * <code>DOTA_COMBATLOG_MODIFIER_ADD = 2;</code>
     */
    public static final int DOTA_COMBATLOG_MODIFIER_ADD_VALUE = 2;
    /**
     * <code>DOTA_COMBATLOG_MODIFIER_REMOVE = 3;</code>
     */
    public static final int DOTA_COMBATLOG_MODIFIER_REMOVE_VALUE = 3;
    /**
     * <code>DOTA_COMBATLOG_DEATH = 4;</code>
     */
    public static final int DOTA_COMBATLOG_DEATH_VALUE = 4;
    /**
     * <code>DOTA_COMBATLOG_ABILITY = 5;</code>
     */
    public static final int DOTA_COMBATLOG_ABILITY_VALUE = 5;
    /**
     * <code>DOTA_COMBATLOG_ITEM = 6;</code>
     */
    public static final int DOTA_COMBATLOG_ITEM_VALUE = 6;
    /**
     * <code>DOTA_COMBATLOG_LOCATION = 7;</code>
     */
    public static final int DOTA_COMBATLOG_LOCATION_VALUE = 7;
    /**
     * <code>DOTA_COMBATLOG_GOLD = 8;</code>
     */
    public static final int DOTA_COMBATLOG_GOLD_VALUE = 8;
    /**
     * <code>DOTA_COMBATLOG_GAME_STATE = 9;</code>
     */
    public static final int DOTA_COMBATLOG_GAME_STATE_VALUE = 9;
    /**
     * <code>DOTA_COMBATLOG_XP = 10;</code>
     */
    public static final int DOTA_COMBATLOG_XP_VALUE = 10;
    /**
     * <code>DOTA_COMBATLOG_PURCHASE = 11;</code>
     */
    public static final int DOTA_COMBATLOG_PURCHASE_VALUE = 11;
    /**
     * <code>DOTA_COMBATLOG_BUYBACK = 12;</code>
     */
    public static final int DOTA_COMBATLOG_BUYBACK_VALUE = 12;
    /**
     * <code>DOTA_COMBATLOG_ABILITY_TRIGGER = 13;</code>
     */
    public static final int DOTA_COMBATLOG_ABILITY_TRIGGER_VALUE = 13;
    /**
     * <code>DOTA_COMBATLOG_PLAYERSTATS = 14;</code>
     */
    public static final int DOTA_COMBATLOG_PLAYERSTATS_VALUE = 14;
    /**
     * <code>DOTA_COMBATLOG_MULTIKILL = 15;</code>
     */
    public static final int DOTA_COMBATLOG_MULTIKILL_VALUE = 15;
    /**
     * <code>DOTA_COMBATLOG_KILLSTREAK = 16;</code>
     */
    public static final int DOTA_COMBATLOG_KILLSTREAK_VALUE = 16;
    /**
     * <code>DOTA_COMBATLOG_TEAM_BUILDING_KILL = 17;</code>
     */
    public static final int DOTA_COMBATLOG_TEAM_BUILDING_KILL_VALUE = 17;
    /**
     * <code>DOTA_COMBATLOG_FIRST_BLOOD = 18;</code>
     */
    public static final int DOTA_COMBATLOG_FIRST_BLOOD_VALUE = 18;
    /**
     * <code>DOTA_COMBATLOG_MODIFIER_REFRESH = 19;</code>
     */
    public static final int DOTA_COMBATLOG_MODIFIER_REFRESH_VALUE = 19;


    public final int getNumber() { return value; }

    public static DOTA_COMBATLOG_TYPES valueOf(int value) {
      switch (value) {
        case 0: return DOTA_COMBATLOG_DAMAGE;
        case 1: return DOTA_COMBATLOG_HEAL;
        case 2: return DOTA_COMBATLOG_MODIFIER_ADD;
        case 3: return DOTA_COMBATLOG_MODIFIER_REMOVE;
        case 4: return DOTA_COMBATLOG_DEATH;
        case 5: return DOTA_COMBATLOG_ABILITY;
        case 6: return DOTA_COMBATLOG_ITEM;
        case 7: return DOTA_COMBATLOG_LOCATION;
        case 8: return DOTA_COMBATLOG_GOLD;
        case 9: return DOTA_COMBATLOG_GAME_STATE;
        case 10: return DOTA_COMBATLOG_XP;
        case 11: return DOTA_COMBATLOG_PURCHASE;
        case 12: return DOTA_COMBATLOG_BUYBACK;
        case 13: return DOTA_COMBATLOG_ABILITY_TRIGGER;
        case 14: return DOTA_COMBATLOG_PLAYERSTATS;
        case 15: return DOTA_COMBATLOG_MULTIKILL;
        case 16: return DOTA_COMBATLOG_KILLSTREAK;
        case 17: return DOTA_COMBATLOG_TEAM_BUILDING_KILL;
        case 18: return DOTA_COMBATLOG_FIRST_BLOOD;
        case 19: return DOTA_COMBATLOG_MODIFIER_REFRESH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DOTA_COMBATLOG_TYPES>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DOTA_COMBATLOG_TYPES>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DOTA_COMBATLOG_TYPES>() {
            public DOTA_COMBATLOG_TYPES findValueByNumber(int number) {
              return DOTA_COMBATLOG_TYPES.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return skadistats.clarity.wire.common.proto.DotaUserMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final DOTA_COMBATLOG_TYPES[] VALUES = values();

    public static DOTA_COMBATLOG_TYPES valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DOTA_COMBATLOG_TYPES(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DOTA_COMBATLOG_TYPES)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036dota_usermessages_common.proto*\360\004\n\024DOT" +
      "A_COMBATLOG_TYPES\022\031\n\025DOTA_COMBATLOG_DAMA" +
      "GE\020\000\022\027\n\023DOTA_COMBATLOG_HEAL\020\001\022\037\n\033DOTA_CO" +
      "MBATLOG_MODIFIER_ADD\020\002\022\"\n\036DOTA_COMBATLOG" +
      "_MODIFIER_REMOVE\020\003\022\030\n\024DOTA_COMBATLOG_DEA" +
      "TH\020\004\022\032\n\026DOTA_COMBATLOG_ABILITY\020\005\022\027\n\023DOTA" +
      "_COMBATLOG_ITEM\020\006\022\033\n\027DOTA_COMBATLOG_LOCA" +
      "TION\020\007\022\027\n\023DOTA_COMBATLOG_GOLD\020\010\022\035\n\031DOTA_" +
      "COMBATLOG_GAME_STATE\020\t\022\025\n\021DOTA_COMBATLOG" +
      "_XP\020\n\022\033\n\027DOTA_COMBATLOG_PURCHASE\020\013\022\032\n\026DO",
      "TA_COMBATLOG_BUYBACK\020\014\022\"\n\036DOTA_COMBATLOG" +
      "_ABILITY_TRIGGER\020\r\022\036\n\032DOTA_COMBATLOG_PLA" +
      "YERSTATS\020\016\022\034\n\030DOTA_COMBATLOG_MULTIKILL\020\017" +
      "\022\035\n\031DOTA_COMBATLOG_KILLSTREAK\020\020\022%\n!DOTA_" +
      "COMBATLOG_TEAM_BUILDING_KILL\020\021\022\036\n\032DOTA_C" +
      "OMBATLOG_FIRST_BLOOD\020\022\022#\n\037DOTA_COMBATLOG" +
      "_MODIFIER_REFRESH\020\023B;\n$skadistats.clarit" +
      "y.wire.common.protoB\020DotaUserMessages\200\001\000"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
